##  Forward stable eigenvalue decomposition of real symmetric arrowhead matrices and rank-one modifications of diagonal matrices

Fakulteta za matematiko in fiziko - Univerza v Ljubljani


Ivan Slapničar, Sveučilište u Splitu, FESB

April 19, 2017

### Outline

* Algorithms, errors and perturbation theory
* Eigenvalue problem and perturbation theory
* Standard algorithms and errors
* Arrowhead and DPR1 matrices
    * inverses
    * algorithm and errors
* Extensions - Hermitian case, half-arrowhead SVD, SVD updating, TDC, Polynomials

### Algorithms, errors and perturbations

Let the value of the function $f(x)$ be computed using $\mathrm{alg(x)}$.

__The (forward) error__ is

$$
\|\mathrm{alg(x)}-f(x)\|,
$$

and __the relative error__ is 

$$
\frac{\| \mathrm{alg}(x)-f(x)\|}{\| f(x) \|}.
$$

### Perturbation theory

The change in $f(x)$ w.r.t. change of $x$ to $x+\delta x$ is

$$
\| f(x+\delta x)-f(x)\| \leq \frac{\| f(x+\delta x)-f(x)\|}{\| \delta x \|} \|\delta x\| \equiv \kappa \|\delta x\|.
$$

$\kappa$ is the __condition number__ (or __condition__) - reminds us of derivative.

Similarly, the _relative_ change in $f(x)$ w.r.t. _relative_ change of $x$ to $x+\delta x$ is

$$
\frac{\| f(x+\delta x)-f(x)\|}{\| f(x) \|}\leq \frac{\| f(x+\delta x)-f(x)\|\cdot  \|x\| }{\|\delta x\| \cdot\| f(x)\|}
\cdot \frac{\|\delta x\|}{\|x\|} \equiv \kappa \frac{\|\delta x\|}{\|x\|}
$$

### Backward errors

Forward erros are hard to estimate.

Instead, we consider  __backward error__

$$
\mathrm{alg}(x)=f(x+\delta x).
$$

Algorithm is __stable__ if  this always holds for some _small_ $\delta x$.

### Eigenvalues and eigenvectors

Let $F=\mathbb{R}$ or $F=\mathbb{C}$ and let $A\in F^{n\times n}$.

If $\exists (\lambda,x) \in F\times F^n$, such that $n\neq 0$ and

$$
Ax=\lambda x,
$$

then $\lambda$ is an __eigenvalue__ of $A$ and $x$ is an __eigenvector__ of $\lambda$.

### Schur decomposition


__Schur decomposition__ of $A$ is 

$$A=QTQ^*,$$

where $Q$ is unitary and $T$ is upper triangular. It always exists.

If $A$ is __normal__ ($AA^*=A^*A$), then $T$ is diagonal.

If, in addition, $A$ is __Hermitian__ ($A=A^*$), then $T$ is also real.

If, in addition, $A$ is real (real symmetric), then $Q$ is real, $A=Q\Lambda Q^T$.

### Perturbation theory

Notation: $\tilde A=A+\Delta A$ with eigenvalues $\tilde \Lambda$, $\tau$ is a permutation, 
$\kappa(A)=\|A\| \|A^{-1}\|$, $\sigma(A)$ is the spectrum of $A$.

__General__: $\|\Lambda- \tilde\Lambda_\tau\|_2\leq 4(\|A\|_2+\|\tilde A\|_2)^{1-1/n}\|\Delta A\|_2^{1/n}$

__Diagonalizable__ _(Bauer-Fike)_: If $A=X\Lambda X^{-1}$, then 

$$
\max_i\min_j |\tilde \lambda_i -
\lambda_j|\leq \|X^{-1}(\Delta A)X\|_p\leq \kappa_p(X)\|\Delta A\|_p
$$

### Perturbation theory

__Both diagonalizable__:
$\|\Lambda-\tilde\Lambda_\tau\|_F\leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_F
$

$\Lambda$ and  $\tilde\Lambda$ real:
$
\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\|_{2,F} \leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_{2,F}
$

__Normal__:
$
\|\Lambda-\tilde\Lambda_\tau\|_F\leq\sqrt{n}\|\Delta A\|_F
$


__Both normal__ _(Hoffman-Wielandt)_:
$
\|\Lambda-\tilde\Lambda_\tau\|_F\leq\|\Delta A\|_F
$


### Perturbation theory


__Both Hermitian__: for any unitarily invariant norm 
$\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\| \leq \|\Delta A\|$

In particular,

\begin{align*}
\max_i|\lambda^\uparrow_i-\tilde\lambda^\uparrow_i|&\leq \|\Delta A\|_2\\ 
\sqrt{\sum_i(\lambda^\uparrow_i-\tilde\lambda^\uparrow_i)^2}&\leq \|\Delta A\|_F
\end{align*}


### Residual bounds for Hermitian matrices

For some $\tilde\lambda\in\mathbb{R}$ and $\tilde x\in\mathbb{C}^n$, $\|\tilde x\|_2=1$, define __residual__ 
$
r=A\tilde x-\tilde\lambda\tilde x
$.

Then $|\tilde\lambda-\lambda|\leq \|r\|_2$ for some $\lambda\in\sigma(A)$.

Let, in addition,  $\tilde\lambda=\tilde x^* A\tilde x$, let $\lambda$ be closest to $\tilde\lambda$ and $x$ be its unit eigenvector, and let 
$$\eta=\mathop{\mathrm{gap}}(\tilde\lambda)= \min_{\lambda\neq\mu\in\sigma(A)}|\tilde\lambda-\mu|.$$
If $\eta>0$, then

$$ |\tilde\lambda-\lambda|\leq \frac{\|r\|_2^2}{\eta},\quad \sin\theta(x,\tilde x)\leq \frac{\|r\|_2}{\eta}.
$$


### Algorithms - Power method

$A$ is real symmetric and $A=U\Lambda U^T$ is its EVD.

__Power method__ starts from vector $x_0$ and computes the sequences

$$
\nu_k=x_k^T A x_k, \qquad x_{k+1}= A x_k /
 \| A x_k \|, \qquad k=0,1,2,\dots
$$

If $|\lambda_1|> |\lambda_2| \geq \cdots \geq |\lambda_n|$,
and if  $x_0=\sum c_i U_{:i}$, then

$$
|\lambda_1-\nu_k|\approx \left|\frac{c_2}{c_1}\right| \left|
 \frac{\lambda_2}{\lambda_1}\right|^k,\qquad
\|U_{:1}-x_k\|_2 =O\bigg(\bigg|
 \frac{\lambda_2}{\lambda_1}\bigg|^k\bigg)\!.
$$

### Inverse iteration

is the power method applied to the inverse of
a _shifted matrix_:

$$
\nu_k=x_k^T A x_k, \
x_{k+1}= (A-\mu I)^{-1} x_k, \ 
x_{k+1} = x_{k+1}/\|x_{k+1}\|, \ k=0,1,2,\dots
$$

Notice $A-\mu I=U(\Lambda-\mu I) U^T$.  

Inverse iteration requires solving the system of linear equations 
$(A-\mu I)x_{k+1}= x_k$ in each step. 

If $\mu$ is very close to some $\lambda_i$, then $|\lambda_i-\mu|\gg
|\lambda_j-\mu|$ for all $j\neq i$, so the convergence is fast.
The solutions of linear systems may have large errors. However, these errors are almost
entirely in the direction of the dominant eigenvector so the method is accurate.

###  QR iteration

starts from the matrix $A_0=A$ and forms the sequence of matrices

$$
  A_k=Q_kR_k \ \textrm{(factorization)}, \quad
  A_{k+1}=R_kQ_k,\quad k=0,1,2,\ldots 
$$

__Shifted QR iteration__ is the QR iteration applied to a shifted matrix:

$$
A_k-\mu I=Q_kR_k \ \textrm{(factorization)}, \quad
  A_{k+1}=R_kQ_k+\mu I ,\quad k=0,1,2,\ldots 
$$

QR iteration is essentially equivalent to the power method and the shifted QR iteration is essentially equivalent to the inverse power method. 

### Practical QR method

1. Reduce $A$ to tridiagonal form $T$ by orthogonal similarities, $X^TAX=T$
2. Compute the EVD of $T$, $T=Q\Lambda Q^T$ 
3. Multiply $U=XQ$

There are many methods for step 2: QR iterations, bisection and inverse iteration, D&C, MRRR, all requiring $O(n^2)$ operations.

### Error bounds

All previous methods have backward errors s.t. $\| \Delta A \| \leq O(\epsilon) \|A\|$.

More precisely, let $\tilde U \tilde \Lambda \tilde U^T$ be the computed EVDs of $A$.
Then

$$
|\lambda_i-\tilde \lambda_i|\leq \phi \epsilon\|A\|_2,
\qquad
\|u_i-\tilde u_i\|_2\leq \psi\epsilon \frac{\|A\|_2}
{\min_{j\neq i} 
|\lambda_i-\tilde \lambda_j|}
$$

$\epsilon$ is machine precision, $\phi$ and $\psi$
are slowly growing polynomial functions of
$n$ (typically $O(n)$ or $O(n^2)$).
Such bounds are obtained by combining perturbation bounds with the floating-point error analysis of the respective
algorithm.


### Relative perturbation theory

$A$  is a real symmetric positive definite (PD) matrix, $\lambda_i>0$.

The __scaled matrix__ of $A$ is the matrix
$A_S=D^{-1} A D^{-1}$, $D=\mathop{\mathrm{diag}}(\sqrt{A_{11}},\sqrt{A_{22}},\ldots,\sqrt{A_{nn}})$.

This scaling is nearly optimal: 
$\kappa_2(A_S)\leq  n \min\limits_{D=\mathrm{diag}} \kappa(DAD) \leq n\kappa_2(A)$.

If $\tilde A=A+\Delta A$ is PD, then [Demmel, Barlow, Veselić, Drmač, Li,...] 

$$
\frac{|\lambda_i-\tilde\lambda_i|}{\lambda_i}\leq 
\frac{\| D^{-1} (\Delta A) D^{-1}\|_2}{\lambda_{\min} (A_S)}\equiv
\|A_S^{-1}\|_2 \| \Delta A_S\|_2.
$$

### Relative perturbation theory

If $\lambda_i$ and $\tilde\lambda_i$ are simple, then

$$
\|U_{:,i}-\tilde U_{:,i}\|_2 \leq \frac{\| A_S^{-1}\|_2 \|\Delta A_S\|_2}
{\displaystyle\min_{j\neq i}\frac{|\lambda_i-\lambda_j|}{\sqrt{\lambda_i\lambda_j}}}.
$$

These bounds are much sharper than the standard bounds when $\kappa_2(A_S)\ll \kappa_2(A)$.

### Jacobi method and relative error bounds

__Jacobi method__ forms a sequence of matrices,

$$
A_0=A, \qquad A_{k+1}=G(i_k,j_k,c,s) A_k G(i_k,j_k,c,s)^T, \qquad
k=1,2,\ldots,
$$

where $G(i_k,j_k,c,s)$ is the orthogonal __plane rotation matrix__, and $c$ and $s$ are chosen such that 
$[A_{k+1}]_{i_k j_k}=[A_{k+1}]_{j_k i_k}=0$.

Jacobi method with the relative stopping criterion $|A_{ij}|\leq tol \sqrt{A_{ii}A_{jj}}$ for all $i\neq j$ (usually $tol=n\varepsilon$), computes the EVD with small __scaled__ backward error $\|\Delta A_S\|\leq \varepsilon\, O(\|A_S\|_2)\leq O(n)\varepsilon$, __provided__ that $\kappa_2([A_k]_S)$  does not grow much during the iterations. [Demmel, Veselić]

In [1]:
function myJacobi{T}(A::Array{T})
    n,m=size(A)
    U=eye(T,n)
    # Tolerance for rotation
    tol=sqrt(n)*eps(T)
    # Counters
    p=n*(n-1)/2
    sweep=0
    pcurrent=0
    # First criterion is for standard accuracy, second one is for relative accuracy
    # while sweep<30 && vecnorm(A-diagm(diag(A)))>tol
    while sweep<30 && pcurrent<p
        sweep+=1
        # Row-cyclic strategy
        for i = 1 : n-1 
            for j = i+1 : n
                # Check the tolerance - the first criterion is standard,
                # the second one is for relative accuracy for PD matrices               
                # if A[i,j]!=zero(T)
                if abs(A[i,j])>tol*sqrt(abs(A[i,i]*A[j,j]))
                    # Compute c and s
                    τ=(A[i,i]-A[j,j])/(2*A[i,j])
                    t=sign(τ)/(abs(τ)+sqrt(1+τ^2))
                    c=1/sqrt(1+t^2)
                    s=c*t
                    G=LinAlg.Givens(i,j,c,s)
                    A=G*A
                    # @show
                    A*=G'
                    A[i,j]=zero(T)
                    A[j,i]=zero(T)
                    U*=G'
                    pcurrent=0
                else
                    pcurrent+=1
                end
            end
        end
    end
    # λ, U
    # @show A
    diag(A), U
end

myJacobi (generic function with 1 method)

In [2]:
n=6
A=rand(-9:9,n,n)
A=A*A'

6×6 Array{Int64,2}:
 135   57   17   19   -2    6
  57   99  -30  -21   43   44
  17  -30  122   95  -10   -6
  19  -21   95   91  -11   25
  -2   43  -10  -11  208  -11
   6   44   -6   25  -11   86

In [3]:
AS=map(Float64,[A[i,j]/sqrt(A[i,i]*A[j,j]) for i=1:n, j=1:n])

6×6 Array{Float64,2}:
  1.0         0.493049   0.132465    0.171422  -0.0119352   0.0556846
  0.493049    1.0       -0.272976   -0.221249   0.299653    0.476854 
  0.132465   -0.272976   1.0         0.901619  -0.0627752  -0.0585763
  0.171422   -0.221249   0.901619    1.0       -0.079954    0.282599 
 -0.0119352   0.299653  -0.0627752  -0.079954   1.0        -0.0822454
  0.0556846   0.476854  -0.0585763   0.282599  -0.0822454   1.0      

In [4]:
cond(AS), cond(A)

(394.89918180565354,466.89082763889917)

In [5]:
# Strong scaling
D=exp(50*(rand(n)-0.5))

6-element Array{Float64,1}:
 3.29585e10
 3.87633   
 1.06779e-8
 6.42495e6 
 4.18419e-8
 2.69236e6 

In [6]:
A=diagm(D)*AS*diagm(D)

6×6 Array{Float64,2}:
   1.08626e21   6.2991e10   46.6181       …  -16.4593        4.94123e15
   6.2991e10   15.026       -1.12988e-8        4.86018e-8    4.97668e6 
  46.6181      -1.12988e-8   1.14017e-16      -2.8047e-17   -0.00168399
   3.62997e16  -5.51025e6    0.0618555        -0.0214942     4.88846e12
 -16.4593       4.86018e-8  -2.8047e-17        1.75075e-15  -0.00926523
   4.94123e15   4.97668e6   -0.00168399   …   -0.00926523    7.24879e12

In [7]:
cond(A)

8.811608949836465e35

In [8]:
λ,U=myJacobi(A)

([1.08626e21,5.24415,1.99874e-18,4.07327e13,1.23511e-15,6.56047e12],
[1.0 -6.38296e-11 … 6.16806e-19 1.60319e-7; 5.79888e-11 1.0 … -9.71366e-9 8.6994e-7; … ; -1.51522e-20 9.76457e-9 … 0.999048 -9.41521e-16; 4.54884e-6 -8.37826e-7 … 9.08627e-15 0.99021])

In [9]:
λ

6-element Array{Float64,1}:
 1.08626e21 
 5.24415    
 1.99874e-18
 4.07327e13 
 1.23511e-15
 6.56047e12 

In [10]:
U

6×6 Array{Float64,2}:
  1.0          -6.38296e-11   9.44341e-20  …   6.16806e-19   1.60319e-7 
  5.79888e-11   1.0          -1.37894e-9      -9.71366e-9    8.6994e-7  
  4.29161e-20   9.53884e-10   0.999048        -0.043623     -1.56914e-15
  3.34171e-5    2.88831e-7   -2.04315e-15     -2.32947e-15  -0.139588   
 -1.51522e-20   9.76457e-9    0.043623         0.999048     -9.41521e-16
  4.54884e-6   -8.37826e-7    2.54806e-15  …   9.08627e-15   0.99021    

In [11]:
λ1,U1=eig(A)

([1.08626e21,4.07327e13,6.56047e12,5.24414,1.72808e-15,4.83419e-9],
[-1.0 3.37249e-5 … -6.20339e-19 3.08109e-16; -5.79888e-11 1.69053e-7 … 9.76459e-9 -4.82696e-6; … ; 1.51522e-20 5.40634e-16 … -1.0 -2.40384e-7; -4.54884e-6 -0.139588 … -9.19446e-15 4.04546e-12])

In [12]:
[sort(λ) sort(λ1)]

6×2 Array{Float64,2}:
 1.99874e-18  1.72808e-15
 1.23511e-15  4.83419e-9 
 5.24415      5.24414    
 6.56047e12   6.56047e12 
 4.07327e13   4.07327e13 
 1.08626e21   1.08626e21 

In [13]:
# Check with BigFloat
λ2,U2=myJacobi(map(BigFloat,A))

(BigFloat[1.08626161638771899420580831533537333697671880262213862431424020520432325102539e+21,5.244145160466330413081771372746375838125783933298937905212113041298934014672389,1.998739487791781598072674936948428601540768362310798697676298730608933205139271e-18,4.073274106254348345584263063285539430782624090016773345269366357901348521031922e+13,1.235110389022941449511702160424458929649703114670959230599947614674921064109702e-15,6.560474304338998830331024489044751811327231855547026558706103609927874116282841e+12],
BigFloat[9.999999994313039480111977055345097092478668803620605598319653151211874786954992e-01 -6.382956548267296831824921118396704867213101765102467914587686626703837303301411e-11 … 6.168055679492958671830825123166598274089282739930356992422910809450114852840839e-19 1.603187281352188186770960885266589082879574768678914110338729269831829329353016e-07; 5.798881515937713044390597211011325356597965167591010234695250846221227252502995e-11 9.9999999999960726429298691043985966850126529

In [14]:
eps(BigFloat)

1.727233711018888925077270372560079914223200072887256277004740694033718360632485e-77

In [16]:
setprecision(256)

256

In [17]:
# Relative error is eps()*cond(AS)
(sort(λ2)-sort(λ))./sort(λ2)

6-element Array{BigFloat,1}:
 -1.907389371593347242641881929858412961917410598838005138858001427671287828316911e-14
 -5.447396434043765303477238417307909747411833149223448529759861879586572941614633e-16
 -5.250427942686647899072792308848010787228033255808995442157030926267615231889769e-16
 -9.225676673267259379031158166668136734789526084338278159912638309919979758780357e-16
 -2.143645907836164614725677789552845972766558116263262407149707914629301421287089e-16
 -2.806563235645517268954805694280000771290752715461615660373656779004123831448778e-16

###  Indefinite matrices

__Spectral absolute value__ is $|A|_{spr}=(A^2)^{1/2}$ (PD part of the polar decomposition of $A$).

The relative perturbation bounds for PD matrices essentially hold with $A_S^{-1}$ replaced by $[|A|_{spr}]_S^{-1}$.

Jacobi method can be modified to compute the EVD with small backward error  $\| \Delta |A|_S\|_2$. [S.]

### Singular value decomposition

Let $A\in\mathbb{C}^{m\times n}$ and let $q=\min\{m,n\}$.

The SVD of $A$ is $A=U\Sigma V^*$,
where $U\in\mathbb{C}^{m\times m}$ and $V\in\mathbb{C}^{n\times n}$ are unitary, and 
$\Sigma=\mathop{\mathrm{diag}}(\sigma_1,\sigma_2,\ldots,\sigma_q)\in\mathbb{R}^{m\times n}$ with all 
$\sigma_j\geq 0$.

SVD is related to EVDs $A^*A=V\Sigma^T\Sigma V^*$ and $AA^*=U\Sigma\Sigma^TU^*$. Eigenvalues of 
the __Jordan-Wielandt__ matrix 

$$
J=\begin{bmatrix}0 & A \\ A^* & 0 \end{bmatrix}
\in \mathbb{C}^{(m+n) \times (m+n)},
$$

are $\pm \sigma_1(A), \pm\sigma_2(A), \cdots,\pm\sigma_q(A)$ together with $|m-n|$ zeros.


### Perturbation theory

Bounds analogous to those for PD matrices hold, for example _(Mirsky)_: 
$\|\Sigma-\tilde\Sigma\|_2\leq \|\Delta A\|_2$ and  $\|\Sigma-\tilde\Sigma\|_F\leq \|\Delta A\|_F$.

Relative perturbation bounds involve __graded__ matrices $A=GD$, where $D=\mathrm{\mathop{diag}}(\| A_{:i}\|_2$, and are efficient when $\kappa(G)\ll \kappa(A)$, for example [Demmel, Veselić, Drmač,...]

$$
\frac{|\sigma_i-\tilde\sigma_i|}{\sigma_i}\leq 
\|G^{\dagger}\|_2 \| \Delta G\|_2.
$$

### Algorithms and error bounds

Standard algorithm is 

1. Reduce $A$ to bidiagonal form $B$, $X^TAY=B$
2. Compute the SVD of $B$, $B=Z\Sigma Q^T$ 
3. Multiply $U=XZ$ and $V=YQ$

Step 1 can preserve relative accuracy [Barlow, Bosner, Drmač].
Step 2 can preserve high relative accuracy [Demmel, Kahan - LAPACK dbdsqr.f, SIAG/LA Prize 1991]

One-sided Jacobi computes the SVD with high relative accuracy [DDGESVD], [Drmač, Veselić - LAPACK dgesvj.f, SIAG/LA Prize 2009]


### Acyclic matrices

Matrices whose bipartite graph is acyclic preserve their singular values under small componentwise perturbations [Demmel, Gragg]. Examples are

1. bidiagonal matrix (path)
2. half-arrowhead matrix (star)

For example, $\varepsilon$ relative changes in diagonal and super-diagonal elements of bidiagonal matrix, cause at most $(2n-1)\varepsilon$ relative changes in the singular values.

In [18]:
# Singular values of a Jordan block - Veselić
n=100
# The starting matrix
a=0.5*ones(n)
b=ones(n-1)
A=Bidiagonal(a,b, true)

100×100 Bidiagonal{Float64}:
 0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅  

In [19]:
σ=svdvals(A)
U,σ1,V=svd(A)
[σ σ1]

100×2 Array{Float64,2}:
 1.49984      1.49984    
 1.49935      1.49935    
 1.49853      1.49853    
 1.49739      1.49739    
 1.49592      1.49592    
 1.49412      1.49412    
 1.492        1.492      
 1.48956      1.48956    
 1.48679      1.48679    
 1.4837       1.4837     
 1.48029      1.48029    
 1.47656      1.47656    
 1.47251      1.47251    
 ⋮                       
 0.556938     0.556938   
 0.547576     0.547576   
 0.538931     0.538931   
 0.531049     0.531049   
 0.523973     0.523973   
 0.517744     0.517744   
 0.512401     0.512401   
 0.507979     0.507979   
 0.504507     0.504507   
 0.502009     0.502009   
 0.500503     0.500503   
 5.91646e-31  2.04866e-30

In [20]:
(σ-σ1)./σ

100-element Array{Float64,1}:
  0.0        
  2.96189e-16
  1.48175e-16
  1.48288e-16
  1.48434e-16
  1.48612e-16
  0.0        
  2.98134e-16
  4.48034e-16
  4.48967e-16
  6.00002e-16
  3.00759e-16
  1.50793e-16
  ⋮          
  0.0        
  0.0        
  2.06005e-16
 -8.36249e-16
 -2.11886e-16
 -4.2887e-16 
 -4.33341e-16
 -2.18557e-16
  0.0        
  0.0        
  2.21821e-16
 -2.46264    

### Arrowhead and DPR1 matrices



__Arrowhead__: 
$A=\begin{bmatrix} D & z \\ z^{T} & \alpha \end{bmatrix}$,
$D=\mathop{\mathrm{diag}}(d_{1}, \ldots ,d_{n-1})$, 
$z=\begin{bmatrix} \zeta _{1} & \cdots & \zeta _{n-1} \end{bmatrix}^T$,
$\alpha\in\mathbb{R}$

__DPR1__: $A= D +\rho z z^T$, $D=\mathop{\mathrm{diag}}(d_{1},\ldots ,d_{n})$, 
$z=\begin{bmatrix} \zeta _{1} & \cdots & \zeta _{n} \end{bmatrix}^T$, $\rho \neq 0\in\mathbb{R}$

If $\zeta _{i}=0$, then $(d_{i},e_{i})$ is an eigenpair. If $d_{i}=d_{j}$, then $d_{i}$ is
an eigenvalue since $\zeta_j$ can be annihilated by a Givens rotation in the $(i,j)$-plane.

Matrices are __irreducible__ if 
$\zeta _{i}\neq 0$ for all $i$ and $d_{i}\neq d_{j}$ for all $i\neq j$.

### Interlacing

Let $A=U\Lambda U^T$ be the EVD of an irreducible arrowhead.
If $d_i$ and $\lambda_i$ are nonincreasingy ordered, then

$$\lambda _{1}> d_{1}> \lambda _{2}> d_{2}> \cdots > d_{n-2}>\lambda
_{n-1}> d_{n-1}> \lambda _{n}.
$$

Let $A=U\Lambda U^T$ be the EVD of an irreducible DPR1. 
If $d_i$ and $\lambda_i$ are nonincreasingy ordered, then

$$\lambda _{1}> d_{1}> \lambda _{2}> d_{2}> \cdots > d_{n-2}>\lambda
_{n-1}> d_{n-1}> \lambda _{n}> d_n.
$$



### Arrowhead EVD

The eigenvalues $\lambda_i$ are the zeros of the __Pick function__ [Stewart, O'Leary]

$$
f(\lambda )=\alpha -\lambda -\sum_{i=1}^{n-1}\frac{\zeta _{i}^{2}}{%
d_{i}-\lambda }=\alpha -\lambda -z^{T}(D-\lambda I)^{-1}z,
$$

and the corresponding eigenvectors are 

$$
U_{:,i}=\frac{x_{i}}{\left\Vert x_{i}\right\Vert _{2}},\quad 
x_{i}=\begin{bmatrix}
\left( D-\lambda _{i}I\right) ^{-1}z \\ 
-1%
\end{bmatrix}, 
\quad i=1,\ldots ,n.
$$

### DPR1 EVD

The eigenvalues of $A$ are the zeros of the __secular equation__ 

$$
f(\lambda )=1+\rho\sum_{i=1}^{n}\frac{\zeta _{i}^{2}}{d_{i}-\lambda }
=1 +\rho z^{T}(D-\lambda I)^{-1}z=0,
$$

and the corresponding eigenvectors are 

$$
U_{:,i}=\frac{x_{i}}{\left\Vert x_{i}\right\Vert _{2}},\quad
x_{i}=( D-\lambda _{i}I) ^{-1}z.
$$

The obvious $O(n)$ algorithms (per eigenpair) are inaccurate.

### Structured inverses (arrowhead)

If $d_i\neq 0$ for all $i$, then

$$
A^{-1}=\begin{bmatrix} D^{-1} &  \\ & 0 \end{bmatrix} + \rho uu^{T}, \
u=\begin{bmatrix} z^{T}D^{-1} \\ -1 \end{bmatrix}, \ \rho =\displaystyle\frac{1}{\alpha-z^{T}D^{-1}z}.
$$

This and subsequent inverses are each computable in $O(n)$ flops.

### Structured inverses (arrow. with zero pole)

If $d_i=0$, then

$$
A^{-1}\equiv 
\begin{bmatrix}
D_{1} & 0 & 0 & z_{1} \\ 
0 & 0 & 0 & \zeta _{i} \\ 
0 & 0 & D_{2} & z_{2} \\ 
z_{1}^{T} & \zeta _{i} & z_{2}^{T} & \alpha
\end{bmatrix}^{-1}
= \begin{bmatrix}
D_{1}^{-1} & w_{1} & 0 & 0 \\ 
w_{1}^{T} & b & w_{2}^{T} & 1/\zeta _{i} \\ 
0 & w_{2} & D_{2}^{-1} & 0 \\ 
0 & 1/\zeta _{i} & 0 & 0
\end{bmatrix},
$$

$w_{1}=-D_{1}^{-1}z_{1}\displaystyle\frac{1}{\zeta _{i}}$, 
$w_{2}=-D_{2}^{-1}z_{2}\displaystyle\frac{1}{\zeta _{i}}$,
$b= \displaystyle\frac{1}{\zeta _{i}^{2}}\left(-\alpha +z_{1}^{T}D_{1}^{-1}z_{1}+z_{2}^{T}D_{2}^{-1}z_{2}\right)$.

### Structured inverses (DPR1)

If $d_i\neq 0$ for all $i$, then

$$
A^{-1}=D^{-1} +\gamma uu^{T},\quad  u=D^{-1}z, \quad \gamma =-\frac{\rho}{1+\rho z^{T}D^{-1}z}.
$$ 

### Structured inverses (DPR1 with $d_i=0$)

$$
A^{-1}\equiv \left(\begin{bmatrix} D_{1} & 0 & 0 \\  0 & 0 & 0  \\  0 & 0 & D_{2} \end{bmatrix}
+\rho \begin{bmatrix} z_{1} \\ \zeta _{i} \\ z_{2}
\end{bmatrix}
\begin{bmatrix}
z_{1}^{T} & \zeta _{i} & z_{2}^{T}
\end{bmatrix}\right)^{-1}=
\begin{bmatrix}
D_{1}^{-1} & w_{1} & 0 \\ 
w_{1}^{T} & b & w_{2}^{T} \\ 
0 & w_{2} & D_{2}^{-1} 
\end{bmatrix},
$$

$w_{1}=-D_{1}^{-1}z_{1}\displaystyle\frac{1}{\zeta _{i}}$,
$w_{2}=-D_{2}^{-1}z_{2}\displaystyle\frac{1}{\zeta _{i}}$,
$b =\displaystyle\frac{1}{\zeta _{i}^{2}}\left(
\frac{1}{\rho}+z_{1}^{T}D_{1}^{-1}z_{1}+z_{2}^{T}D_{2}^{-1}z_{2}\right)$.

### Idea

Let $\lambda_\max$ be the absolutely largest eigenvalue. 

It is computed with high relative accuracy by any reasonable algorithm:

$$
\frac{\big|\lambda_\max -\tilde \lambda_\max\big|}{\big|\lambda_\max\big|}\leq 
\frac{\|\Delta A\|_2}{\big|\lambda_\max\big|}=
\frac{\epsilon \|A\|_2}{\big|\lambda_\max\big|}\equiv \epsilon.
$$

### Algorithms

The algorithms based on the following approach compute all eigenvalues and _all components_ of the corresponding eigenvectors in a forward stable manner to almost full accuracy in $O(n)$ operations per eigenpair [Jakovčević Stor, Barlow, S.]:

1. Shift the irreducible $A$ to $d_i$ which is closer to $\lambda_i$ (one step of bisection on $f(\lambda)$).
2. Invert the shifted matrix. 
3. Compute the absolutely largest eigenvalue of the inverted shifted matrix and the corresponding eigenvector.

### Numerical issues

1. All elements of the inverses of the shifted matrices are highly accurate, except possibly $b$ (or $\rho$ or $\gamma$). If these are not accurate, compute them using extended precision.

2. If two eigenvalues are close to the same pole, one much nearer than the other, some modifications are necessary. 

The algorithms are implemented in the package [Arrowhead.jl](https://github.com/ivanslapnicar/Arrowhead.jl). 

For double the working the package [DoubleDouble.jl](https://github.com/simonbyrne/DoubleDouble.jl) is used.

In [21]:
using Arrowhead

In [22]:
whos(Arrowhead)

                     Arrowhead     30 KB     Module
                  GenHalfArrow      0 bytes  Arrowhead.#GenHalfArrow
                   GenSymArrow      0 bytes  Arrowhead.#GenSymArrow
                    GenSymDPR1      0 bytes  Arrowhead.#GenSymDPR1
                     HalfArrow    180 bytes  DataType
                      SymArrow    204 bytes  DataType
                       SymDPR1    192 bytes  DataType
                        bisect      0 bytes  Arrowhead.#bisect
                           eig      0 bytes  Base.LinAlg.#eig
                           inv      0 bytes  Base.#inv
                      rootsWDK      0 bytes  Arrowhead.#rootsWDK
                       rootsah      0 bytes  Arrowhead.#rootsah
                           svd      0 bytes  Base.LinAlg.#svd
                           tdc      0 bytes  Arrowhead.#tdc


In [23]:
methods(GenSymArrow)

# 1 method for generic function "GenSymArrow":
GenSymArrow(n::Integer, i::Integer) at C:\Users\Ivan\.julia\v0.5\Arrowhead\src\arrowhead3.jl:8

In [24]:
n=10
A=GenSymArrow(n,n)

10×10 Arrowhead.SymArrow{Float64}:
 0.251722   0.0       0.0       0.0       …  0.0       0.0       0.0331726
 0.0        0.559182  0.0       0.0          0.0       0.0       0.811757 
 0.0        0.0       0.845298  0.0          0.0       0.0       0.444126 
 0.0        0.0       0.0       0.921409     0.0       0.0       0.101049 
 0.0        0.0       0.0       0.0          0.0       0.0       0.428597 
 0.0        0.0       0.0       0.0       …  0.0       0.0       0.471424 
 0.0        0.0       0.0       0.0          0.0       0.0       0.4991   
 0.0        0.0       0.0       0.0          0.915905  0.0       0.574678 
 0.0        0.0       0.0       0.0          0.0       0.282592  0.645209 
 0.0331726  0.811757  0.444126  0.101049     0.574678  0.645209  0.30809  

In [25]:
fieldnames(A)

4-element Array{Symbol,1}:
 :D
 :z
 :a
 :i

In [26]:
A.D, A.z, A.a, A.i

([0.251722,0.559182,0.845298,0.921409,0.797279,0.0487064,0.992224,0.915905,0.282592],[0.0331726,0.811757,0.444126,0.101049,0.428597,0.471424,0.4991,0.574678,0.645209],0.30808956771580354,10)

In [27]:
tols=[1e2,1e2,1e2,1e2,1e2]
U,λ=eig(A,tols)
norm(full(A)*U-U*diagm(λ)), norm(U'*U-I)

(2.0010109520344182e-15,6.327421139988411e-16)

In [28]:
# Timings - notice the O(n^2)
@time eig(GenSymArrow(1000,1000),tols);
@time eig(GenSymArrow(2000,2000),tols);

  0.381110 seconds (1.09 M allocations: 121.123 MB, 8.20% gc time)
  0.987643 seconds (4.12 M allocations: 476.543 MB, 14.85% gc time)


In [29]:
# Numerically demanding matrix
A=SymArrow( [ 1e10+1.0/3.0, 4.0, 3.0, 2.0, 1.0 ], 
[ 1e10 - 1.0/3.0, 1.0, 1.0, 1.0, 1.0 ], 1e10, 6 )

6×6 Arrowhead.SymArrow{Float64}:
 1.0e10  0.0  0.0  0.0  0.0  1.0e10
 0.0     4.0  0.0  0.0  0.0  1.0   
 0.0     0.0  3.0  0.0  0.0  1.0   
 0.0     0.0  0.0  2.0  0.0  1.0   
 0.0     0.0  0.0  0.0  1.0  1.0   
 1.0e10  1.0  1.0  1.0  1.0  1.0e10

In [30]:
U,λ=eig(A,tols)
λ

6-element Array{Float64,1}:
  2.0e10  
  4.17472 
  3.18832 
  2.22325 
  1.26185 
 -0.348142

In [31]:
U

6×6 Array{Float64,2}:
 -0.707107      0.16715     0.175055    0.201186   0.230118    0.589904
 -3.53553e-11  -0.956659    0.21567     0.113232   0.0840413   0.135668
 -3.53553e-11  -0.142289   -0.929569    0.25901    0.132392    0.176188
 -3.53553e-11  -0.0768603  -0.147313   -0.901161   0.31175     0.251222
 -3.53553e-11  -0.0526502  -0.0799952  -0.164468  -0.878813    0.437568
 -0.707107     -0.16715    -0.175055   -0.201186  -0.230118   -0.589904

In [32]:
λ1,U1=eig(full(A))
λ1

6-element Array{Float64,1}:
 -0.348142
  1.26185 
  2.22325 
  3.18832 
  4.17472 
  2.0e10  

In [33]:
U1

6×6 Array{Float64,2}:
 -0.589904   0.230118   -0.201186   0.175055    0.16715    -0.707107   
 -0.135668   0.0840414  -0.113232   0.21567    -0.956659   -3.53553e-11
 -0.176188   0.132392   -0.25901   -0.929568   -0.142289   -3.53553e-11
 -0.251222   0.31175     0.901161  -0.147313   -0.0768603  -3.53553e-11
 -0.437568  -0.878813    0.164468  -0.0799953  -0.0526502  -3.53553e-11
  0.589904  -0.230118    0.201186  -0.175055   -0.16715    -0.707107   

In [34]:
(sort(λ)-sort(λ1))./sort(λ)

6-element Array{Float64,1}:
  1.17284e-6 
 -4.90798e-8 
 -2.13464e-8 
 -1.12719e-8 
 -7.84919e-9 
 -1.71661e-15

In [35]:
U[2,1]

-3.5355339066398446e-11

In [36]:
U1[end-1,end]

-3.5355274263793035e-11

In [37]:
# Numerically demanding DPR1 matrix
A=SymDPR1( [ 10.0/3.0, 2.0+1e-7, 2.0-1e-7, 1.0 ], [ 2.0, 1e-7, 1e-7, 2.0], 1.0 )
A = SymDPR1( [ 1e10, 5.0, 4e-3, 0.0, -4e-3,-5.0 ], [ 1e10, 1.0, 1.0, 1e-7, 1.0,1.0 ], 1.0 )

6×6 Arrowhead.SymDPR1{Float64}:
    1.0e20  1.0e10  1.0e10  1000.0      1.0e10   1.0e10
    1.0e10  6.0     1.0        1.0e-7   1.0      1.0   
    1.0e10  1.0     1.004      1.0e-7   1.0      1.0   
 1000.0     1.0e-7  1.0e-7     1.0e-14  1.0e-7   1.0e-7
    1.0e10  1.0     1.0        1.0e-7   0.996    1.0   
    1.0e10  1.0     1.0        1.0e-7   1.0     -4.0   

In [38]:
fieldnames(A)

3-element Array{Symbol,1}:
 :D
 :u
 :r

In [39]:
U,λ=eig(A,tols)
norm(full(A)*U-U*diagm(λ)), norm(U'*U-I)

Remedy 3 


(3.0381820397056514e-6,2.2204460858891437e-16)

In [40]:
[sort(λ) sort(eigvals(full(A)))]

6×2 Array{Float64,2}:
 -5.0      -5.0        
 -0.004    -5.74215e-14
  1.0e-24   5.62712e-14
  0.004     0.004      
  5.0       5.0        
  1.0e20    1.0e20     

### Hermitian case

Let $H=\begin{bmatrix}
D & r \\
r^{*} & \alpha
\end{bmatrix}$, $r\in\mathbb{C}^{n-1}$. Then

$$
A=\begin{bmatrix}
D & z \\
z^{T} & \alpha
\end{bmatrix}, \ 
\Delta =\mathop{\mathrm{diag}}\big(\frac{r_{1}}{\left\vert r_{1}\right\vert },\ldots ,\frac{r_{n-1}%
}{\left\vert r_{n-1}\right\vert },1\big) \\
A=V\Lambda V^{T}\Rightarrow
H=U\Lambda U^{*}, U=\Delta V.
$$

### Singular value decomposition

$$
B=\begin{bmatrix}
D & z \\ 
0  & \alpha
\end{bmatrix}, \quad
A=B^TB=\begin{bmatrix}
D^2 & Dz \\ 
z^T D   & \alpha+z^T z
\end{bmatrix}$$

With proper implementation we ensure that all entries of $A_i^{-1}$ 
are computed to high relative accuracy, for example 

$$
[A_i^{-1}]_{jj}=\frac{1}{(d_j-d_i)(d_j+d_i)}, \quad j\neq i.
$$

Compute the $k$-th eigenpair $(\lambda,v)$ of $A$.
Then $(u,\sigma=\sqrt{\lambda},v)$ is the SV triplet of $B$.

From $U^T B=\Sigma V^T$ for the $k$-th row we have

$$
\begin{bmatrix} u_{1:n-1}^T & u_n
\end{bmatrix}
\begin{bmatrix} D & z \\ 0 & \alpha
\end{bmatrix}=\sigma \begin{bmatrix} v_{1:n-1}^T & v_n
\end{bmatrix}, \ u_{1:n-1}= \sigma v_{1:n-1} D^{-1}.
$$

From $BV=U\Sigma $ for the $k$-th column we have

$$
\begin{bmatrix} D & z \\ 0 & \alpha
\end{bmatrix}
\begin{bmatrix} v_{1:n-1} \\ v_n
\end{bmatrix}
=\sigma \begin{bmatrix} u_{1:n-1} \\ u_n
\end{bmatrix}, \
u_n= \frac{\alpha v_n}{\sigma}.
$$

In [41]:
A=GenHalfArrow(8,8)

8×8 Arrowhead.HalfArrow{Float64}:
 0.146609   0.0        0.0        …   0.0        0.0       -0.257869  
 0.0       -0.127191   0.0            0.0        0.0       -0.00524706
 0.0        0.0       -0.0442389      0.0        0.0        0.275445  
 0.0        0.0        0.0            0.0        0.0       -0.0579225 
 0.0        0.0        0.0            0.0        0.0        0.293094  
 0.0        0.0        0.0        …  -0.371219   0.0       -0.260795  
 0.0        0.0        0.0            0.0       -0.355073  -0.0318741 
 0.0        0.0        0.0            0.0        0.0        0.267537  

In [42]:
U,Σ,V=svd(A,tols)

Remedy 3 


(
[0.391393 0.0187291 … -0.0505361 -0.0316466; 0.00785872 0.000362699 … -0.00159118 -0.000868031; … ; 0.0656799 0.984148 … -0.000784861 -0.000643542; -0.385211 -0.016125 … -0.121878 -0.750876],

[0.646922,0.35542,0.32936,0.172854,0.127205,0.113978,0.080407,0.0300082],
[0.0886996 0.00772565 … -0.0921442 -0.154614; -0.0015451 -0.000129796 … 0.002517 0.00367921; … ; -0.0360494 -0.983187 … 0.00346591 0.00761475; -0.931466 -0.0214219 … -0.0366298 -0.0842216],

[1,2,2,3,5,5,6,7],[1.0,2.18493,2.18493,1.56461,6.68125,6.68125,5.40719,4.62462],[1.0,8.55412,8.55412,1.70991,145.063,145.063,20.511,7.94494],[26.7351,1.19279,85.1289,1.43668,1.06532,991.32,1.30469,1.49146],[0.0,0.0,0.0,0.0,0.0,14.9988,0.0,0.0],[0,0,0,0,0,0,0,0])

In [43]:
vecnorm(A*V-U*diagm(Σ)), vecnorm(U'*U-I), vecnorm(V'*V-I)

(1.7769127543209654e-16,1.442998490456321e-15,6.110570913244331e-16)

### SVD updating

Let $A=U\Sigma V^T\in\mathbb{R}^{m\times n}$ with $m\geq n$ and $\mathop{\mathrm{rank}}(A)=n$.
Then

$$\begin{bmatrix} A \\ a^T\end{bmatrix} =\begin{bmatrix} U & \\ & 1 \end{bmatrix} 
\begin{bmatrix} \Sigma \\ a^TV \end{bmatrix}  V^T= \\
=\begin{bmatrix} U & \\ & 1 \end{bmatrix} \bar U \bar\Sigma \bar V^T V^T \equiv
\tilde U \bar \Sigma \tilde V^T.
$$
      
Computation of $\tilde U$ and $\tilde V$ requires $O(mn^2)+O(n^3)$ flops. One can 
also use FMM [Gu, Eisenstat]  which is "not for the timid" [Johnson].

In [44]:
function mySVDaddrow{T}(svdA::Tuple,a::Vector{T})
    # Create the transposed half-arrowhead
    m,r,n=size(svdA[1],1),length(svdA[2]),size(svdA[3],1)
    b=svdA[3]'*a
    if m>=n || r<m
        M=HalfArrow(svdA[2],b)
    else
        β=sqrt(vecnorm(a)^2-vecnorm(b)^2)
        M=HalfArrow(svdA[2],[b;β])
    end
    tols=[1e2,1e2,1e2,1e2]
    U,σ,V=svd(M,tols)
    # Return the updated SVD
    if m>=n || r<m
        return [svdA[1] zeros(T,m); zeros(T,1,r) one(T)]*V, σ, svdA[3]*U
    else
        # Need one more row of svdA[3] - v is orthogonal projection
        v=a-svdA[3]*b
        v=v/norm(v)
        return [svdA[1] zeros(T,m); zeros(T,1,r) one(T)]*V, σ, [svdA[3] v]*U
    end
end

mySVDaddrow (generic function with 1 method)

In [45]:
# Adding row to a tall matrix
A=rand(10,6)
a=rand(6)

6-element Array{Float64,1}:
 0.666597
 0.317071
 0.917819
 0.781676
 0.809385
 0.288552

In [46]:
svdA=svd(A)

(
[-0.439303 -0.269777 … 0.390162 0.0828828; -0.19086 -0.314697 … -0.207524 0.119187; … ; -0.252734 -0.53299 … -0.298892 0.196406; -0.331345 0.527455 … -0.480323 -0.210955],

[4.09566,1.2773,1.07608,0.729069,0.601654,0.418239],
[-0.404627 0.194671 … -0.0311387 -0.445498; -0.194368 0.363396 … -0.802658 0.206557; … ; -0.529891 0.440275 … 0.525729 0.468035; -0.502513 -0.505668 … -0.259422 0.374237])

In [47]:
typeof(svdA)

Tuple{Array{Float64,2},Array{Float64,1},Array{Float64,2}}

In [48]:
U,σ,V=mySVDaddrow(svdA,a)

(
[-0.409075 0.28388 … -0.413502 0.136002; -0.176031 0.326869 … 0.211038 0.00731488; … ; -0.314744 -0.533504 … 0.461212 -0.196933; -0.355818 -0.179562 … -0.192752 -0.409158],

[4.37637,1.29503,1.09904,0.817148,0.613834,0.535585],
[-0.408228 -0.189292 … -0.258219 -0.595476; -0.196589 -0.367699 … 0.875736 0.00935183; … ; -0.530036 -0.42033 … -0.311158 0.666496; -0.461323 0.604744 … 0.260258 0.142186])

In [49]:
# Check the residual and orthogonality
norm([A;a']*V-U*diagm(σ)), norm(U'*U-I), norm(V'*V-I)

(1.876226815825556e-15,1.3263025706643674e-15,1.7000563291971699e-15)

In [50]:
# Adding row to a flat matrix
A=rand(6,10)
a=rand(10)
svdA=svd(A)

(
[-0.325947 -0.318571 … -0.467468 0.612393; -0.555825 0.19249 … -0.265271 -0.466661; … ; -0.307898 0.39308 … -0.483899 0.0137117; -0.320671 -0.122381 … 0.232491 -0.445308],

[3.89811,1.16079,0.833261,0.680474,0.60711,0.512597],
[-0.379908 -0.0270757 … -0.283916 0.482979; -0.403166 0.542484 … -0.152198 -0.344853; … ; -0.390828 0.0304739 … 0.75037 -0.0500027; -0.220651 0.157168 … 0.00202965 -0.137812])

In [51]:
U,σ,V=mySVDaddrow(svdA,a)
norm([A;a']*V-U*diagm(σ)), norm(U'*U-I), norm(V'*V-I)

Remedy 3 


(5.357160034874592e-15,8.93167302461745e-16,2.9674723977498678e-15)

In [52]:
# Adding colums is adding rows to the transpose
function mySVDaddcol{T}(svdA::Tuple,a::Vector{T})
    reverse(mySVDaddrow(reverse(svdA),a))
end 

mySVDaddcol (generic function with 1 method)

In [53]:
# Flat matrix
A=rand(6,10)
a=rand(6)
svdA=svd(A)
U,σ,V=mySVDaddcol(svdA,a)
norm([A a]*V-U*diagm(σ)), norm(U'*U-I), norm(V'*V-I)

(1.6278725152295515e-15,1.8833672589760425e-15,9.306939896435802e-16)

In [54]:
# Updating low-rank approximation
A=rand(10,6)
svdA=svd(A)
a=rand(6)
# Rank of the approximation
r=4

4

In [55]:
svdAr=(svdA[1][:,1:r], svdA[2][1:r],svdA[3][:,1:r])
U,σ,V=mySVDaddrow(svdAr,a)
norm([A;a']-U*diagm(σ)*V'), svdvals([A;a']), σ

(0.4720653968550853,[3.9901,1.33754,1.19048,0.769958,0.457606,0.407084],[3.98955,1.33734,1.18577,0.769257])

### Trididgonal Divide & Conquer

1. The tridiagonal matrix is split into two halves.
2. EVD if each half is computed.
3. EVDs are merged via SVD of either DPR1 matrix [LAPACK dstedc.f] or arrowhead matrix 
[tdc()](https://github.com/ivanslapnicar/Arrowhead.jl/blob/master/src/arrowhead7.jl).

In [56]:
using MatrixDepot
W=SymTridiagonal(matrixdepot("wilkinson",21))

21×21 SymTridiagonal{Float64}:
 10.0  1.0   ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
  1.0  9.0  1.0   ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅   1.0  8.0  1.0   ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅   1.0  7.0  1.0   ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅   1.0  6.0  1.0   ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅   1.0  5.0  1.0  …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅    ⋅   1.0  4.0      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   1.0      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅     ⋅ 
   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅  

In [57]:
U,λ=tdc(W)
λtrue= [10.746194182903393,
 10.746194182903322,
 9.210678647361332,
 9.210678647304919,
 8.038941122829023,
 8.038941115814273,
 7.003952209528675,
 7.003951798616375,
 6.000234031584167,
 6.000217522257098,
 5.000244425001913,
 4.999782477742902,
 4.004354023440857,
 3.9960482013836245,
 3.0430992925788236,
 2.9610588841857264,
 2.1302092193625057,
 1.7893213526950813,
 0.9475343675292932,
 0.25380581709667804,
 -1.1254415221199847]
(sort(λ)-sort(λtrue))./sort(λtrue)

21-element Array{Float64,1}:
 -3.94591e-16
  0.0        
  1.1717e-16 
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        
  0.0        

### Roots of polynomials

[Fiedler] Let $u\left( x\right) =x^{n}+px^{n-1}+r\left( x\right)$. Let
$D=\mathrm{diag}(d_{1},\ldots,d_{n-1})$,
where $d_j$ are all distinct and $u\left( d_{j}\right) \neq 0$. Let

$$
\alpha =-p-\sum\limits_{j=1}^{n-1}d_{j}, \
z=
\begin{bmatrix}
\zeta_1 & \zeta_2 & \cdots & \zeta_{n-1}
\end{bmatrix}^T, \
\zeta_{j}^{2}= -\frac{u(d_{j})}{\prod_{\substack{ i=1  \\ i\neq j}}^{n-1} ( d_{j}-d_i)}.
$$

Then $A=\begin{bmatrix}
D & z \\
z^{T} & \alpha
\end{bmatrix}$
has characteristic polynomial $\left( -1\right) ^{n}u\left( x\right)$.
If $u\left( x\right) $ has only real distinct roots and the $d_{j}$'s
interlace them, then $A$ is real.

In [60]:
# Chebyshev polynomials
using Polynomials
n=374
T=Array(Any,n+1)
T[1]=Poly([BigInt(1)])
T[2]=Poly([BigInt(0),1])
for i=3:n+1
    T[i]=2*T[2]*T[i-1]-T[i-2]
end

# True zeros
Rtrue=map(Float64,[cos((2*k-1)*pi/(2*n)) for k=1:n])
# Zeros of T[n]
D=map(Float64,[cos((2*k-1)*pi/(2*(n-1))) for k=1:n-1])

# Computed zeros
R,qout=rootsah(T[n+1],D)

([0.999991,0.999921,0.99978,0.999568,0.999286,0.998933,0.99851,0.998016,0.997452,0.996818  …  -0.996818,-0.997452,-0.998016,-0.99851,-0.998933,-0.999286,-0.999568,-0.99978,-0.999921,-0.999991],[0,0,0,0,0,0,0,0,0,0  …  0,0,0,0,0,0,0,0,0,0])

In [61]:
maximum(abs((Rtrue-R)./Rtrue))

4.625953686934833e-14

In [64]:
T[51]

Poly(-1 + 1250*x^2 - 260000*x^4 + 21528000*x^6 - 947232000*x^8 + 25638412800*x^10 - 466152960000*x^12 + 6034375680000*x^14 - 57930006528000*x^16 + 424820047872000*x^18 - 2432653747814400*x^20 + 11057517035520000*x^22 - 40383975260160000*x^24 + 119536566770073600*x^26 - 288405684905574400*x^28 + 568855350917201920*x^30 - 917508630511616000*x^32 + 1206989963132928000*x^34 - 1287455960675123200*x^36 + 1102487181118668800*x^38 - 746299014911098880*x^40 + 390051749953536000*x^42 - 151732604633088000*x^44 + 41341637204377600*x^46 - 7036874417766400*x^48 + 562949953421312*x^50)

### To-do List

1. Implement fast singular vector update via FMM.
2. Consider general matrices (complex symmetric) for EVD or Takagi factorization.


## Thank you!

### Questions?