## Forward stable eigenvalue decomposition of real symmetric arrowhead matrices and rank-one modifications of diagonal matrices

Fakulteta za matematiko in fiziko - Univerza v Ljubljani


Ivan Slapničar, Sveučilište u Splitu, FESB

April 19, 2017

### Outline

* Algorithms, errors and perturbation theory
* Eigenvalue problem and perturbation theory
* Standard algorithms and errors
* Arrowhead matrices
    * inverses
    * algorithm and errors
    * SVD
* DPR1 matrices - algorithms and errors
* Deflation

### Algorithms, errors and perturbations

Let the value of the function $f(x)$ be computed using $\mathrm{alg(x)}$.

__The (forward) error__ is

$$
\|\mathrm{alg(x)}-f(x)\|,
$$

and __the relative error__ is 

$$
\frac{\| \mathrm{alg}(x)-f(x)\|}{\| f(x) \|}.
$$

### Perturbation theory

The change in $f(x)$ w.r.t. change of $x$ to $x+\delta x$ is

$$
\| f(x+\delta x)-f(x)\| \leq \frac{\| f(x+\delta x)-f(x)\|}{\| \delta x \|} \|\delta x\| \equiv \kappa \|\delta x\|.
$$

$\kappa$ is the __condition number__ (or __condition__) - reminds us of derivative.

Similarly, the _relative_ change in $f(x)$ w.r.t. _relative_ change of $x$ to $x+\delta x$ is

$$
\frac{\| f(x+\delta x)-f(x)\|}{\| f(x) \|}\leq \frac{\| f(x+\delta x)-f(x)\|\cdot  \|x\| }{\|\delta x\| \cdot\| f(x)\|}
\cdot \frac{\|\delta x\|}{\|x\|} \equiv \kappa \frac{\|\delta x\|}{\|x\|}
$$

### Backward errors

Forward erros are hard to estimate.

Instead, we consider  __backward error__

$$
\mathrm{alg}(x)=f(x+\delta x).
$$

Algorithms is __stable__ if  this always holds for some _small_ $\delta x$.

### Eigenvalues and eigenvectors

Let $F=\mathbb{R}$ or $F=\mathbb{C}$ and let $A\in F^{n\times n}$.

If $\exists (\lambda,x) \in F\times F^n$, such that $n\neq 0$ and

$$
Ax=\lambda x,
$$

then $\lambda$ is an __eigenvalue__ of $A$ and $x$ is an __eigenvector__ of $\lambda$.

### Schur decomposition


__Schur decomposition__ of $A$ is 

$$A=QTQ^*,$$

where $Q$ is unitary and $T$ is upper triangular. It always exists.

If $A$ is __normal__ ($AA^*=A^*A$), then $T$ is diagonal.

If, in addition, $A$ is __Hermitian__ ($A=A^*$), then $T$ is also real.

If, in addition, $A$ is real (real symmetric), then $Q$ is real, $A=Q\Lambda Q^T$.

### Perturbation theory

Notation: $\tilde A=A+\Delta A$ with eigenvalues $\tilde \Lambda$, $\tau$ is a permutation, 
$\kappa(A)=\|A\| \|A^{-1}\|$, $\sigma(A)$ is the spectrum of $A$.

__General__: $\|\Lambda- \tilde\Lambda_\tau\|_2\leq 4(\|A\|_2+\|\tilde A\|_2)^{1-1/n}\|\Delta A\|_2^{1/n}$

__Diagonalizable__ _(Bauer-Fike)_: If $A=X\Lambda X^{-1}$, then 

$$
\max_i\min_j |\tilde \lambda_i -
\lambda_j|\leq \|X^{-1}(\Delta A)X\|_p\leq \kappa_p(X)\|\Delta A\|_p
$$

### Perturbation theory

__Both diagonalizable__:
$\|\Lambda-\tilde\Lambda_\tau\|_F\leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_F
$

$\Lambda$ and  $\tilde\Lambda$ real:
$
\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\|_{2,F} \leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_{2,F}
$

__Normal__:
$
\|\Lambda-\tilde\Lambda_\tau\|_F\leq\sqrt{n}\|\Delta A\|_F
$


__Both normal__ _(Hoffman-Wielandt)_:
$
\|\Lambda-\tilde\Lambda_\tau\|_F\leq\|\Delta A\|_F
$


### Perturbation theory


__Both Hermitian__: for any unitarily invariant norm 
$\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\| \leq \|\Delta A\|$

In particular,

\begin{align*}
\max_i|\lambda^\uparrow_i-\tilde\lambda^\uparrow_i|&\leq \|\Delta A\|_2\\ 
\sqrt{\sum_i(\lambda^\uparrow_i-\tilde\lambda^\uparrow_i)^2}&\leq \|\Delta A\|_F
\end{align*}


### Residual bounds for Hermitian matrices

For some $\tilde\lambda\in\mathbb{R}$ and $\tilde x\in\mathbb{C}^n$, $\|\tilde x\|_2=1$, define __residual__ 
$
r=A\tilde x-\tilde\lambda\tilde x
$.

Then $|\tilde\lambda-\lambda|\leq \|r\|_2$ for some $\lambda\in\sigma(A)$.

Let, in addition,  $\tilde\lambda=\tilde x^* A\tilde x$, let $\lambda$ be closest to $\tilde\lambda$ and $x$ be its unit eigenvector, and let 
$$\eta=\mathop{\mathrm{gap}}(\tilde\lambda)= \min_{\lambda\neq\mu\in\sigma(A)}|\tilde\lambda-\mu|.$$
If $\eta>0$, then

$$ |\tilde\lambda-\lambda|\leq \frac{\|r\|_2^2}{\eta},\quad \sin\theta(x,\tilde x)\leq \frac{\|r\|_2}{\eta}.
$$


### Algorithms - Power method

$A$ is real symmetric and $A=U\Lambda U^T$ is its EVD.

__Power method__ starts from vector $x_0$ and computes the sequences

$$
\nu_k=x_k^T A x_k, \qquad x_{k+1}= A x_k /
 \| A x_k \|, \qquad k=0,1,2,\dots
$$

If $|\lambda_1|> |\lambda_2| \geq \cdots \geq |\lambda_n|$,
and if  $x_0=\sum c_i U_{:i}$, then

$$
|\lambda_1-\nu_k|\approx \left|\frac{c_2}{c_1}\right| \left|
 \frac{\lambda_2}{\lambda_1}\right|^k,\qquad
\|U_{:1}-x_k\|_2 =O\bigg(\bigg|
 \frac{\lambda_2}{\lambda_1}\bigg|^k\bigg)\!.
$$

### Inverse iteration

is the power method applied to the inverse of
a _shifted matrix_:

$$
\nu_k=x_k^T A x_k, \
x_{k+1}= (A-\mu I)^{-1} x_k, \ 
x_{k+1} = x_{k+1}/\|x_{k+1}\|, \ k=0,1,2,\dots
$$

Notice $A-\mu I=U(\Lambda-\mu I) U^T$.  

Inverse iteration requires solving the system of linear equations 
$(A-\mu I)x_{k+1}= x_k$ in each step. 

If $\mu$ is very close to some $\lambda_i$, then $|\lambda_i-\mu|\gg
|\lambda_j-\mu|$ for all $j\neq i$, so the convergence is fast.
The solutions of linear systems may have large errors. However, these errors are almost
entirely in the direction of the dominant eigenvector so the method is accurate.

###  QR iteration

starts from the matrix $A_0=A$ and forms the sequence of matrices

$$
  A_k=Q_kR_k \ \textrm{(factorization)}, \quad
  A_{k+1}=R_kQ_k,\quad k=0,1,2,\ldots 
$$

__Shifted QR iteration__ is the QR iteration applied to a shifted matrix:

$$
A_k-\mu I=Q_kR_k \ \textrm{(factorization)}, \quad
  A_{k+1}=R_kQ_k+\mu I ,\quad k=0,1,2,\ldots 
$$

QR iteration is essentially equivalent to the power method and the shifted QR iteration is essentially equivalent to the inverse power method. 

### Practical QR method

1. Reduce $A$ to tridiagonal form $T$ by orthogonal similarities, $X^TAX=T$
2. Compute the EVD of $T$, $T=Q\Lambda Q^T$ 
3. Multiply $U=XQ$

There are many methods for step 2: QR iterations, bisection and inverse iteration, D&C, MRRR, all requiring $O(n^2)$ operations.

### Error bounds

All previous methods have backward errors s.t. $\| \Delta A \| \leq O(\epsilon) \|A\|$.

More precisely, let $\tilde U \tilde \Lambda \tilde U^T$ be the computed EVDs of $A$.
Then

$$
|\lambda_i-\tilde \lambda_i|\leq \phi \epsilon\|A\|_2,
\qquad
\|u_i-\tilde u_i\|_2\leq \psi\epsilon \frac{\|A\|_2}
{\min_{j\neq i} 
|\lambda_i-\tilde \lambda_j|}
$$

$\epsilon$ is machine precision, $\phi$ and $\psi$
are slowly growing polynomial functions of
$n$ (typically $O(n)$ or $O(n^2)$).
Such bounds are obtained by combining perturbation bounds with the floating-point error analysis of the respective
algorithm.


### Relative perturbation theory

$A$  is a real symmetric positive definite (PD) matrix, $\lambda_i>0$.

The __scaled matrix__ of $A$ is the matrix
$A_S=D^{-1} A D^{-1}$, $D=\mathop{\mathrm{diag}}(\sqrt{A_{11}},\sqrt{A_{22}},\ldots,\sqrt{A_{nn}})$.

This scaling is nearly optimal: 
$\kappa_2(A_S)\leq  n \min\limits_{D=\mathrm{diag}} \kappa(DHD) \leq n\kappa_2(H)$.

If $\tilde A=A+\Delta A$ is PD, then [Demmel, Barlow, Veselić, Drmač, Li,...] 

$$
\frac{|\lambda_i-\tilde\lambda_i|}{\lambda_i}\leq 
\frac{\| D^{-1} (\Delta A) D^{-1}\|_2}{\lambda_{\min} (A_S)}\equiv
\|A_S^{-1}\|_2 \| \Delta A_S\|_2.
$$

### Relative perturbation theory

If $\lambda_i$ and $\tilde\lambda_i$ are simple, then

$$
\|U_{:,i}-\tilde U_{:,i}\|_2 \leq \frac{\| A_S^{-1}\|_2 \|\Delta A_S\|_2}
{\displaystyle\min_{j\neq i}\frac{|\lambda_i-\lambda_j|}{\sqrt{\lambda_i\lambda_j}}}.
$$

These bounds are much sharper than the standard bounds when $\kappa_2(A_S)\ll \kappa_2(A)$.

### Jacobi method and relative error bounds

__Jacobi method__ forms a sequence of matrices,

$$
A_0=A, \qquad A_{k+1}=G(i_k,j_k,c,s) A_k G(i_k,j_k,c,s)^T, \qquad
k=1,2,\ldots,
$$

where $G(i_k,j_k,c,s)$ is the orthogonal __plane rotation matrix__, and $c$ and $s$ are chosen such that 
$[A_{k+1}]_{i_k j_k}=[A_{k+1}]_{j_k i_k}=0$.

Jacobi method with the relative stopping criterion $|A_{ij}|\leq tol \sqrt{A_{ii}A_{jj}}$ for all $i\neq j$ (usually $tol=n\varepsilon$), computes the EVD with small __scaled__ backward error $\|\Delta A_S\|\leq \varepsilon\, O(\|A_S\|_2)\leq O(n)\varepsilon$, __provided__ that $\kappa_2([A_k]_S)$  does not grow much during the iterations. [Demmel, Veselić]

In [1]:
function myJacobi{T}(A::Array{T})
    n,m=size(A)
    U=eye(T,n)
    # Tolerance for rotation
    tol=sqrt(n)*eps(T)
    # Counters
    p=n*(n-1)/2
    sweep=0
    pcurrent=0
    # First criterion is for standard accuracy, second one is for relative accuracy
    # while sweep<30 && vecnorm(A-diagm(diag(A)))>tol
    while sweep<30 && pcurrent<p
        sweep+=1
        # Row-cyclic strategy
        for i = 1 : n-1 
            for j = i+1 : n
                # Check the tolerance - the first criterion is standard,
                # the second one is for relative accuracy for PD matrices               
                # if A[i,j]!=zero(T)
                if abs(A[i,j])>tol*sqrt(abs(A[i,i]*A[j,j]))
                    # Compute c and s
                    τ=(A[i,i]-A[j,j])/(2*A[i,j])
                    t=sign(τ)/(abs(τ)+sqrt(1+τ^2))
                    c=1/sqrt(1+t^2)
                    s=c*t
                    G=LinAlg.Givens(i,j,c,s)
                    A=G*A
                    # @show
                    A*=G'
                    A[i,j]=zero(T)
                    A[j,i]=zero(T)
                    U*=G'
                    pcurrent=0
                else
                    pcurrent+=1
                end
            end
        end
    end
    # λ, U
    # @show A
    diag(A), U
end

myJacobi (generic function with 1 method)

In [2]:
n=6
A=rand(-9:9,n,n)
A=A*A'

6×6 Array{Int64,2}:
 122    2  -21  -76   28   21
   2  132  -17  140   60  -12
 -21  -17   84   15  -37  -67
 -76  140   15  229   50  -59
  28   60  -37   50   82   49
  21  -12  -67  -59   49  148

In [3]:
AS=map(Float64,[A[i,j]/sqrt(A[i,i]*A[j,j]) for i=1:n, j=1:n])

6×6 Array{Float64,2}:
  1.0         0.0157603  -0.207443  -0.454691   0.279944   0.156282 
  0.0157603   1.0        -0.161444   0.805236   0.57671   -0.0858546
 -0.207443   -0.161444    1.0        0.108152  -0.445815  -0.600903 
 -0.454691    0.805236    0.108152   1.0        0.364876  -0.320482 
  0.279944    0.57671    -0.445815   0.364876   1.0        0.444793 
  0.156282   -0.0858546  -0.600903  -0.320482   0.444793   1.0      

In [4]:
cond(AS), cond(A)

(63.531058220405455,64.04177835616379)

In [5]:
# Strong scaling
D=exp(50*(rand(n)-0.5))

6-element Array{Float64,1}:
 7.41721e-5
 1.63375e-7
 6.79371e6 
 3.09305e-7
 1.82297e8 
 6.41459   

In [6]:
A=diagm(D)*AS*diagm(D)

6×6 Array{Float64,2}:
    5.50149e-9    1.9098e-13   -104.531       …  3785.21         7.43563e-5
    1.9098e-13    2.66914e-14    -0.17919          17.176       -8.99741e-8
 -104.531        -0.17919         4.61545e13       -5.52129e14  -2.61866e7 
   -1.04314e-11   4.06908e-14     0.227263         20.5737      -6.35857e-7
 3785.21         17.176          -5.52129e14        3.32321e16   5.20123e8 
    7.43563e-5   -8.99741e-8     -2.61866e7   …     5.20123e8   41.1469    

In [7]:
cond(A)

1.3048631512985587e30

In [8]:
λ,U=myJacobi(A)

([5.02261e-9,2.29512e-15,3.6971e13,3.58443e-14,3.32413e16,24.6824],
[0.999997 -0.00110471 … 1.13907e-13 -1.88135e-7; -0.000339249 0.823785 … 5.16725e-16 -1.24958e-8; … ; -9.66522e-14 1.80376e-16 … 0.999862 -7.7688e-9; 1.88062e-7 -5.71287e-9 … 1.56578e-8 1.0])

In [9]:
λ1,U1=eig(A)

([3.32413e16,3.6971e13,24.6824,-0.000132288,5.50066e-14,0.00252215],
[1.14136e-13 -1.12402e-12 … 9.26906e-8 -7.87273e-10; 2.46992e-16 4.79525e-15 … 9.72615e-12 1.0; … ; 0.999862 0.0166305 … 1.0924e-15 -7.56716e-16; 1.56578e-8 -4.7424e-7 … -2.78688e-8 1.22934e-8])

In [10]:
[sort(λ) sort(λ1)]

6×2 Array{Float64,2}:
  2.29512e-15  -0.000132288
  3.58443e-14   5.50066e-14
  5.02261e-9    0.00252215 
 24.6824       24.6824     
  3.6971e13     3.6971e13  
  3.32413e16    3.32413e16 

In [11]:
# Check with BigFloat
λ2,U2=myJacobi(map(BigFloat,A))

(BigFloat[5.022614877781149125539210164929030420146746773515899696960643187317643046577704e-09,2.295123812804994670064398624978608626094419879330841147247327958758049463352806e-15,3.69709760989353391999716039607013085617023550846726252497535938803637609775443e+13,3.58442908604202048887119888314880706877507542982825120427202388597308838743938e-14,3.324128602639678860975071153952176645799736210731727702874912594775807140907954e+16,2.46823555145719291121145500883882866290457481725366572554375047580039138063829e+01],
BigFloat[9.999969615982539377331101147559754452834275528414717672736964140575748516894691e-01 -1.104713724270534496826238635189559126469097833676912650859732520535158609448299e-03 … 1.139074123223364507094259086863585769557234380818640483261349979571726790219396e-13 -1.881351158755531512751902132523613243002881035801779816506469374670225736025187e-07; -3.392490770226965414700324549475980750803308066749211580480332613491578980333178e-04 8.237854061465595798489599735011879903427

In [12]:
# Relative error is eps()*cond(AS)
(sort(λ2)-sort(λ))./sort(λ2)

6-element Array{BigFloat,1}:
 -2.608544515585232496093839344125106270207557409753143511686891006658419464596948e-15
 -2.194318804006210569268021934621652226307993757473709030414239287652003141389973e-16
 -6.181600905183360108694538884417831953010804722380976622056949928184373641940984e-16
 -8.006272606869755098814876291906572791964006933460485022962800990262987772746052e-16
  8.824412953637573485953240920331026994216541576126251131895845905576149340265213e-17
 -1.01989113350436958664433563068197557638015726028122315319920090332616898843922e-16 

###  Indefinite matrices

__Spectral absolute value__ is $|A|_{spr}=(A^2)^{1/2}$ (PD part of the polar decomposition of $A$).

The relative perturbation bounds for PD matrices essentially hold with $A_S$ replaced by $[|A|_{spr}]_S$.

Jacobi method can be modified to compute the EVD with small backward error  $\| \Delta [|A|_{spr}]_S\|_2$. [S.]

### Singular value decomposition

Let $A\in\mathbb{C}^{m\times n}$ and let $q=\min\{m,n\}$.

The SVD of $A$ is $A=U\Sigma V^*$,
where $U\in\mathbb{C}^{m\times m}$ and $V\in\mathbb{C}^{n\times n}$ are unitary, and 
$\Sigma=\mathop{\mathrm{diag}}(\sigma_1,\sigma_2,\ldots,\sigma_q)\in\mathbb{R}^{m\times n}$ with all 
$\sigma_j\geq 0$.

SVD is related to EVDs $A^*A=V\Sigma^T\Sigma V^*$ and $AA^*=U\Sigma\Sigma^TU^*$. Eigenvalues of 
the __Jordan-Wielandt__ matrix 

$$
J=\begin{bmatrix}0 & A \\ A^* & 0 \end{bmatrix}
\in \mathbb{C}^{(m+n) \times (m+n)},
$$

are $\pm \sigma_1(A), \pm\sigma_2(A), \cdots,\pm\sigma_q(A)$ together with $|m-n|$ zeros.


### Perturbation theory

Bounds analogous to those for PD matrices hold, for example _(Mirsky)_: 
$\|\Sigma-\tilde\Sigma\|_2\leq \|\Delta A\|_2$ and  $\|\Sigma-\tilde\Sigma\|_F\leq \|\Delta A\|_F$.

Relative perturbation bounds involve __graded__ matrices $A=GD$, where $D=\mathrm{\mathop{diag}}(\| A_{:i}\|_2$, and are efficient when $\kappa(G)\ll \kappa(A)$, for example [Demmel, Veselić, Drmač,...]

$$
\frac{|\sigma_i-\tilde\sigma_i|}{\sigma_i}\leq 
\|G^{\dagger}\|_2 \| \Delta G\|_2.
$$

### Algorithms and error bounds

Standard algorithm is 

1. Reduce $A$ to bidiagonal form $B$, $X^TAY=B$
2. Compute the SVD of $B$, $B=Z\Sigma Q^T$ 
3. Multiply $U=XZ$ and $V=YQ$

Step 1 can preserve relative accuracy [Barlow, Bosner, Drmač].
Step 2 can preserve high relative accuracy [Demmel, Kahan - LAPACK dbdsqr.f, SIAG/LA Prize 1991]

One-sided Jacobi computes the SVD with high relative accuracy [DDGESVD], [Drmač, Veselić - LAPACK dgesvj.f, SIAG/LA Prize 2009]


### Acyclic matrices

Matrices whose bipartite graph is acyclic preserve their singular values under small componentwise perturbations [Demmel, Gragg]. Examples are

1. bidiagonal matrix (path)
2. half-arrowhead matrix (star)

For example, $\varepsilon$ relative changes in diagonal and super-diagonal elements of bidiagonal matrix, cause at most $(2n-1)\varepsilon$ relative changes in the singular values.

In [17]:
# Singular values of a Jordan block - Veselić
n=100
# The starting matrix
a=0.5*ones(n)
b=ones(n-1)
A=Bidiagonal(a,b, true)

100×100 Bidiagonal{Float64}:
 0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅  

In [18]:
σ=svdvals(A)
U,σ1,V=svd(A)
[σ σ1]

100×2 Array{Float64,2}:
 1.49984      1.49984    
 1.49935      1.49935    
 1.49853      1.49853    
 1.49739      1.49739    
 1.49592      1.49592    
 1.49412      1.49412    
 1.492        1.492      
 1.48956      1.48956    
 1.48679      1.48679    
 1.4837       1.4837     
 1.48029      1.48029    
 1.47656      1.47656    
 1.47251      1.47251    
 ⋮                       
 0.556938     0.556938   
 0.547576     0.547576   
 0.538931     0.538931   
 0.531049     0.531049   
 0.523973     0.523973   
 0.517744     0.517744   
 0.512401     0.512401   
 0.507979     0.507979   
 0.504507     0.504507   
 0.502009     0.502009   
 0.500503     0.500503   
 5.91646e-31  2.04866e-30

In [20]:
(σ-σ1)./σ

100-element Array{Float64,1}:
  0.0        
  2.96189e-16
  1.48175e-16
  1.48288e-16
  1.48434e-16
  1.48612e-16
  0.0        
  2.98134e-16
  4.48034e-16
  4.48967e-16
  6.00002e-16
  3.00759e-16
  1.50793e-16
  ⋮          
  0.0        
  0.0        
  2.06005e-16
 -8.36249e-16
 -2.11886e-16
 -4.2887e-16 
 -6.50012e-16
 -2.18557e-16
  0.0        
  0.0        
  2.21821e-16
 -2.46264    

### Arrowhead and DPR1 matrices



__Arrowhead__: 
$A=\begin{bmatrix} D & z \\ z^{T} & \alpha \end{bmatrix}$,
$D=\mathop{\mathrm{diag}}(d_{1}, \ldots ,d_{n-1})$, 
$z=\begin{bmatrix} \zeta _{1} & \cdots & \zeta _{n-1} \end{bmatrix}^T$,
$\alpha\in\mathbb{R}$

__DPR1__: $A= D +\rho z z^T$, $D=\mathop{\mathrm{diag}}(d_{1},\ldots ,d_{n})$, 
$z=\begin{bmatrix} \zeta _{1} & \cdots & \zeta _{n} \end{bmatrix}^T$, $\rho \neq 0\in\mathbb{R}$

If $\zeta _{i}=0$, then $(d_{i},e_{i})$ is an eigenpair. If $d_{i}=d_{j}$, then $d_{i}$ is
an eigenvalue since $\zeta_j$ can be annihilated by a Givens rotation in the $(i,j)$-plane.

Matrices are __irreducible__ if 
$\zeta _{i}\neq 0$ for all $i$ and $d_{i}\neq d_{j}$ for all $i\neq j$.

### Interlacing

Let $A=U\Lambda U^T$ be the EVD of an irreducible arrowhead.
If $d_i$ and $\lambda_i$ are nonincreasingy ordered, then

$$\lambda _{1}> d_{1}> \lambda _{2}> d_{2}> \cdots > d_{n-2}>\lambda
_{n-1}> d_{n-1}> \lambda _{n}.
$$

Let $A=U\Lambda U^T$ be the EVD of an irreducible DPR1. 
If $d_i$ and $\lambda_i$ are nonincreasingy ordered, then

$$\lambda _{1}> d_{1}> \lambda _{2}> d_{2}> \cdots > d_{n-2}>\lambda
_{n-1}> d_{n-1}> \lambda _{n}> d_n.
$$



### Arrowhead EVD

The eigenvalues $\lambda_i$ are the zeros of the __Pick function__

$$
f(\lambda )=\alpha -\lambda -\sum_{i=1}^{n-1}\frac{\zeta _{i}^{2}}{%
d_{i}-\lambda }=\alpha -\lambda -z^{T}(D-\lambda I)^{-1}z,
$$

and the corresponding eigenvectors are 

$$
U_{:,i}=\frac{x_{i}}{\left\Vert x_{i}\right\Vert _{2}},\quad 
x_{i}=\begin{bmatrix}
\left( D-\lambda _{i}I\right) ^{-1}z \\ 
-1%
\end{bmatrix}, 
\quad i=1,\ldots ,n.
$$

### DPR1 EVD

The eigenvalues of $A$ are the zeros of the __secular equation__ 

$$
f(\lambda )=1+\rho\sum_{i=1}^{n}\frac{\zeta _{i}^{2}}{d_{i}-\lambda }
=1 +\rho z^{T}(D-\lambda I)^{-1}z=0,
$$

and the corresponding eigenvectors are 

$$
U_{:,i}=\frac{x_{i}}{\left\Vert x_{i}\right\Vert _{2}},\quad
x_{i}=( D-\lambda _{i}I) ^{-1}z.
$$

The obvious $O(n)$ algorithms (per eigenpair) are inaccurate.

### Structured inverses (arrowhead)

If $d_i\neq 0$ for all $i$, then

$$
A^{-1}=\begin{bmatrix} D^{-1} &  \\ & 0 \end{bmatrix} + \rho uu^{T}, \
u=\begin{bmatrix} z^{T}D^{-1} \\ -1 \end{bmatrix}, \ \rho =\displaystyle\frac{1}{\alpha-z^{T}D^{-1}z}.
$$

### Structured inverses (arrow. with zero pole)

If $d_i=0$, then

$$
A^{-1}\equiv 
\begin{bmatrix}
D_{1} & 0 & 0 & z_{1} \\ 
0 & 0 & 0 & \zeta _{i} \\ 
0 & 0 & D_{2} & z_{2} \\ 
z_{1}^{T} & \zeta _{i} & z_{2}^{T} & \alpha
\end{bmatrix}^{-1}
= \begin{bmatrix}
D_{1}^{-1} & w_{1} & 0 & 0 \\ 
w_{1}^{T} & b & w_{2}^{T} & 1/\zeta _{i} \\ 
0 & w_{2} & D_{2}^{-1} & 0 \\ 
0 & 1/\zeta _{i} & 0 & 0
\end{bmatrix},
$$

$w_{1}=-D_{1}^{-1}z_{1}\displaystyle\frac{1}{\zeta _{i}}$, 
$w_{2}=-D_{2}^{-1}z_{2}\displaystyle\frac{1}{\zeta _{i}}$,
$b= \displaystyle\frac{1}{\zeta _{i}^{2}}\left(-\alpha +z_{1}^{T}D_{1}^{-1}z_{1}+z_{2}^{T}D_{2}^{-1}z_{2}\right)$.

### Structured inverses (DPR1)

If $d_i\neq 0$ for all $i$, then

$$
A^{-1}=D^{-1} +\gamma uu^{T},\quad  u=D^{-1}z, \quad \gamma =-\frac{\rho}{1+\rho z^{T}D^{-1}z}.
$$ 

### Structured inverses (DPR1 with zero pole)

If $d_i=0$, then

$$
A^{-1}\equiv \left(\begin{bmatrix} D_{1} & 0 & 0 \\  0 & 0 & 0  \\  0 & 0 & D_{2} \end{bmatrix}
+\rho \begin{bmatrix} z_{1} \\ \zeta _{i} \\ z_{2}
\end{bmatrix}
\begin{bmatrix}
z_{1}^{T} & \zeta _{i} & z_{2}^{T}
\end{bmatrix}\right)^{-1}=
\begin{bmatrix}
D_{1}^{-1} & w_{1} & 0 \\ 
w_{1}^{T} & b & w_{2}^{T} \\ 
0 & w_{2} & D_{2}^{-1} 
\end{bmatrix},
$$

$w_{1}=-D_{1}^{-1}z_{1}\displaystyle\frac{1}{\zeta _{i}}$,
$w_{2}=-D_{2}^{-1}z_{2}\displaystyle\frac{1}{\zeta _{i}}$,
$b =\displaystyle\frac{1}{\zeta _{i}^{2}}\left(
\frac{1}{\rho}+z_{1}^{T}D_{1}^{-1}z_{1}+z_{2}^{T}D_{2}^{-1}z_{2}\right)$.

6. The algorithm based on the following approach computes all eigenvalues and _all components_ of the corresponding eigenvectors in a forward stable manner to almost full accuracy in $O(n)$ operations per eigenpair:
    1. Shift the irreducible $A$ to $d_i$ which is closer to $\lambda_i$ (one step of bisection on $f(\lambda)$).
    2. Invert the shifted matrix.
    3. Compute the absolutely largest eigenvalue of the inverted shifted matrix and the corresponding eigenvector.

7. The algorithm is implemented in the package [Arrowhead.jl](https://github.com/ivanslapnicar/Arrowhead.jl). In certain cases, $b$ or $\rho$ need to be computed with extended precision for which the package 
[DoubleDouble.jl](https://github.com/simonbyrne/DoubleDouble.jl) is used.

* $p$: vjerojatnost da pratimo neki link
* $1-p$:  je vjerojatnost da odemo na neku drugu slučajnu stranicu
* google koristi $p=0.85$ ?

In [4]:
p=0.85
z = ((1-p)*(c.!=0) + (c.==0))/n
A=p*G+ones(n)*z

6×6 Array{Float64,2}:
 0.025  0.025  0.025     0.875  0.166667  0.875
 0.45   0.025  0.025     0.025  0.166667  0.025
 0.025  0.45   0.025     0.025  0.166667  0.025
 0.025  0.45   0.308333  0.025  0.166667  0.025
 0.025  0.025  0.308333  0.025  0.166667  0.025
 0.45   0.025  0.308333  0.025  0.166667  0.025

Krenimo u slučajnu šetnju od vektora $x_0=\begin{bmatrix} 1/n \\ 1/n \\ \vdots \\ 1/n \end{bmatrix}$.

Sljedeći vektori u nizu su 

$$
x_1=A\cdot x_0 \\
x_2=A\cdot x_1 \\
x_3=A\cdot x_2\\
\vdots
$$

Kada se algoritam stabilizira, odnosno kada je 

$$
A\cdot x\approx x,
$$

tada je element vektora $x[i]$ __rang stranice__ $i$.

In [5]:
function myPageRank(G::SparseMatrixCSC{Float64,Int64},steps::Int)
    p=0.85
    c=sum(G,1)/p
    n=size(G,1)
    for i=1:n
        G.nzval[G.colptr[i]:G.colptr[i+1]-1]./=c[i]
    end
    e=ones(n)
    x=e/n
    z = vec(((1-p)*(c.!=0) + (c.==0))/n)
    for j=1:steps
        x=G*x+(z⋅x)
    end
    x/norm(x,1)
end

myPageRank (generic function with 1 method)

In [6]:
myPageRank(G,15)

6-element Array{Float64,1}:
 0.321024 
 0.170538 
 0.106596 
 0.136795 
 0.0643103
 0.200737 

### [Stanford web graph](http://snap.stanford.edu/data/web-Stanford.html)

Malo veći testni problem.

In [7]:
W=readdlm("web-Stanford.txt",Int)

2312497×2 Array{Int64,2}:
      1    6548
      1   15409
   6548   57031
  15409   13102
      2   17794
      2   25202
      2   53625
      2   54582
      2   64930
      2   73764
      2   84477
      2   98628
      2  100193
      ⋮        
 281849  165189
 281849  177014
 281849  226290
 281849  243180
 281849  244195
 281849  247252
 281849  281568
 281865  186750
 281865  225872
 281888  114388
 281888  192969
 281888  233184

In [8]:
S=sparse(W[:,2],W[:,1],1.0)

281903×281903 sparse matrix with 2312497 Float64 nonzero entries:
	[6548  ,      1]  =  1.0
	[15409 ,      1]  =  1.0
	[17794 ,      2]  =  1.0
	[25202 ,      2]  =  1.0
	[53625 ,      2]  =  1.0
	[54582 ,      2]  =  1.0
	[64930 ,      2]  =  1.0
	[73764 ,      2]  =  1.0
	[84477 ,      2]  =  1.0
	[98628 ,      2]  =  1.0
	⋮
	[168703, 281902]  =  1.0
	[180771, 281902]  =  1.0
	[266504, 281902]  =  1.0
	[275189, 281902]  =  1.0
	[44103 , 281903]  =  1.0
	[56088 , 281903]  =  1.0
	[90591 , 281903]  =  1.0
	[94440 , 281903]  =  1.0
	[216688, 281903]  =  1.0
	[256539, 281903]  =  1.0
	[260899, 281903]  =  1.0

In [9]:
@time x100=myPageRank(S,100);

  1.541993 seconds (846.80 k allocations: 542.598 MB, 10.27% gc time)


In [10]:
x101=myPageRank(S,101)
maxabs((x100-x101)./x100)

2.349138102570129e-7

In [11]:
sortperm(x100,rev=true), sort(x101,rev=true)

([89073,226411,241454,262860,134832,234704,136821,68889,105607,69358  …  281647,281700,281715,281728,281778,281785,281813,281849,281865,281888],[0.0113029,0.00926783,0.00829727,0.00302312,0.00300128,0.00257173,0.00245371,0.00243079,0.00239105,0.00236401  …  5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7])

## Doba preporuka 

NetFlix, Amazon Prime, PickBox, ... - on-line videoteke (filmovi i serije)

[NetFlix](https://www.netflix.com/hr/)

 * [80 milijuna korisnika](https://www.statista.com/statistics/250934/quarterly-number-of-netflix-streaming-subscribers-worldwide/), 5.000 filmova
 * [NetFlix Prize](http://www.kdd.org/kdd2014/tutorials/KDD%20-%20The%20Recommender%20Problem%20Revisited.pdf)
 

## Matematika

Netflix Recommendation Engine se temelji na aproksimaciji (velike i rijetke) matrice
```
M = Korisnici x Filmovi 
```
pomoću rastava singularnih vrijednosti (SVD): 

* [IncrementalSVD.jl](https://github.com/aaw/IncrementalSVD.jl)
* [A parallel recommendation engine in Julia](http://juliacomputing.com/blog/2016/04/22/a-parallel-recommendation-engine-in-julia.html)

## Sličnost

Sličnost korisnika $i$ i $k$:
$$
\cos \angle (i,k)=\frac{(M[i,:],M[k,:])}{\|M[i,:]\| \cdot \|M[k,:]\|}
$$
Sličnost filmova $i$ i $k$:
$$
\cos \angle (i,k)=\frac{(M[:,i],M[:,k)}{\|M[:,i]\| \cdot \|M[:,k]\|}
$$

## Pretraživanje

Redak $M[k,:]$ - što korisnik $k$ misli o filmovima.

Stupac $M[:,f]$ - što o filmu $f$ misle korisnici

Element $M[k,f]$ - što korisnik $k$ misli o filmu $f$.

## Problem

Matrica $M$ je rijetka pa nemamo dovoljno informacija. Na primjer, 

```
900188 ocjena / ( 6040 korisnika x 3706 filmova ) = 4%
```

## Aproksimacija

SVD rastav $M=U\Sigma V^T$ se aproksimira matricom jako malog ranga (npr. $m=25$)

![SVD rastav](svd.png)

Približna matrica je puna i daje dovoljno informacija.

Efikasna aproksimacija? -> $\$$ 1.000.000  

In [12]:
# Pkg.clone("git://github.com/aaw/IncrementalSVD.jl.git")

In [13]:
using IncrementalSVD


Use "Dict(a=>b for (a,b) in c)" instead.


In [14]:
whos(IncrementalSVD)

                IncrementalSVD     57 KB     Module
                        Rating    136 bytes  DataType
                     RatingSet    148 bytes  DataType
                  RatingsModel    160 bytes  DataType
             cosine_similarity      0 bytes  IncrementalSVD.#cosine_similarity
          get_predicted_rating      0 bytes  IncrementalSVD.#get_predicted_rati…
                 item_features      0 bytes  IncrementalSVD.#item_features
                   item_search      0 bytes  IncrementalSVD.#item_search
                         items      0 bytes  IncrementalSVD.#items
    load_book_crossing_dataset      0 bytes  IncrementalSVD.#load_book_crossing…
  load_large_movielens_dataset      0 bytes  IncrementalSVD.#load_large_moviele…
  load_small_movielens_dataset      0 bytes  IncrementalSVD.#load_small_moviele…
                          rmse      0 bytes  IncrementalSVD.#rmse
                 similar_items      0 bytes  IncrementalSVD.#similar_items
                 similar_us

In [15]:
rating_set = load_small_movielens_dataset();

Reusing existing downloaded files...
Loading ratings 100% Time: 0:00:03


In [16]:
fieldnames(rating_set)

4-element Array{Symbol,1}:
 :training_set 
 :test_set     
 :user_to_index
 :item_to_index

In [17]:
# Format je (korisnik, film, ocjena)
rating_set.training_set

900188-element Array{IncrementalSVD.Rating,1}:
 IncrementalSVD.Rating(3718,1914,2.0)
 IncrementalSVD.Rating(2078,526,5.0) 
 IncrementalSVD.Rating(2919,284,4.0) 
 IncrementalSVD.Rating(3829,364,3.0) 
 IncrementalSVD.Rating(4887,109,3.0) 
 IncrementalSVD.Rating(4892,377,5.0) 
 IncrementalSVD.Rating(4167,1208,2.0)
 IncrementalSVD.Rating(3868,559,3.0) 
 IncrementalSVD.Rating(5455,920,3.0) 
 IncrementalSVD.Rating(1999,295,5.0) 
 IncrementalSVD.Rating(6016,490,2.0) 
 IncrementalSVD.Rating(899,19,5.0)   
 IncrementalSVD.Rating(4490,1242,5.0)
 ⋮                                   
 IncrementalSVD.Rating(5776,79,4.0)  
 IncrementalSVD.Rating(1425,2435,3.0)
 IncrementalSVD.Rating(2624,23,4.0)  
 IncrementalSVD.Rating(1146,86,2.0)  
 IncrementalSVD.Rating(4715,669,4.0) 
 IncrementalSVD.Rating(3546,1356,3.0)
 IncrementalSVD.Rating(3576,1579,3.0)
 IncrementalSVD.Rating(3792,651,4.0) 
 IncrementalSVD.Rating(1883,393,3.0) 
 IncrementalSVD.Rating(2353,940,2.0) 
 IncrementalSVD.Rating(5035,427,5.0) 
 In

In [18]:
rating_set.test_set

100021-element Array{IncrementalSVD.Rating,1}:
 IncrementalSVD.Rating(3272,157,3.0) 
 IncrementalSVD.Rating(883,128,5.0)  
 IncrementalSVD.Rating(840,105,4.0)  
 IncrementalSVD.Rating(2402,1107,2.0)
 IncrementalSVD.Rating(5364,1299,5.0)
 IncrementalSVD.Rating(4448,774,4.0) 
 IncrementalSVD.Rating(678,995,4.0)  
 IncrementalSVD.Rating(3684,1388,3.0)
 IncrementalSVD.Rating(149,406,4.0)  
 IncrementalSVD.Rating(4854,27,4.0)  
 IncrementalSVD.Rating(3821,8,2.0)   
 IncrementalSVD.Rating(1752,185,5.0) 
 IncrementalSVD.Rating(2015,237,4.0) 
 ⋮                                   
 IncrementalSVD.Rating(3557,1364,1.0)
 IncrementalSVD.Rating(1232,742,4.0) 
 IncrementalSVD.Rating(2860,429,3.0) 
 IncrementalSVD.Rating(1266,3121,3.0)
 IncrementalSVD.Rating(4050,1498,4.0)
 IncrementalSVD.Rating(3669,464,4.0) 
 IncrementalSVD.Rating(1745,1071,4.0)
 IncrementalSVD.Rating(3754,2871,2.0)
 IncrementalSVD.Rating(4072,1477,4.0)
 IncrementalSVD.Rating(687,1086,1.0) 
 IncrementalSVD.Rating(934,1409,2.0) 
 In

In [19]:
# Korisnici i njihove šifre
rating_set.user_to_index

Dict{AbstractString,Int32} with 6040 entries:
  "4304" => 4304
  "3935" => 3935
  "5422" => 5422
  "5734" => 5734
  "2243" => 2243
  "1881" => 1881
  "5425" => 5425
  "4209" => 4209
  "1907" => 1907
  "2923" => 2923
  "599"  => 599
  "2491" => 2491
  "5944" => 5944
  "228"  => 228
  "2590" => 2590
  "3697" => 3697
  "5031" => 5031
  "2579" => 2579
  "5551" => 5551
  "1880" => 1880
  "2562" => 2562
  "3215" => 3215
  "3991" => 3991
  "4652" => 4652
  "4088" => 4088
  ⋮      => ⋮

In [20]:
# Filmovi i njihove šifre
rating_set.item_to_index

Dict{AbstractString,Int32} with 3706 entries:
  "Fried Green Tomatoes (1991)"                                       => 594
  "Milk Money (1994)"                                                 => 1361
  "From Russia with Love (1963)"                                      => 729
  "House II: The Second Story (1987)"                                 => 1247
  "Held Up (2000)"                                                    => 3549
  "Missing in Action 2: The Beginning (1985)"                         => 2177
  "Murder, My Sweet (1944)"                                           => 996
  "Hidden, The (1987)"                                                => 981
  "Cable Guy, The (1996)"                                             => 669
  "Big Kahuna, The (2000)"                                            => 893
  "Addams Family Values (1993)"                                       => 1857
  "Farinelli: il castrato (1994)"                                     => 1945
  "Education of Little T

In [21]:
# Možemo posebno izvaditi naslove ...
keys(rating_set.item_to_index)

Base.KeyIterator for a Dict{AbstractString,Int32} with 3706 entries. Keys:
  "Fried Green Tomatoes (1991)"
  "Milk Money (1994)"
  "From Russia with Love (1963)"
  "House II: The Second Story (1987)"
  "Held Up (2000)"
  "Missing in Action 2: The Beginning (1985)"
  "Murder, My Sweet (1944)"
  "Hidden, The (1987)"
  "Cable Guy, The (1996)"
  "Big Kahuna, The (2000)"
  "Addams Family Values (1993)"
  "Farinelli: il castrato (1994)"
  "Education of Little Tree, The (1997)"
  "In God's Hands (1998)"
  "Last Man Standing (1996)"
  "Sixth Sense, The (1999)"
  "Star Maps (1997)"
  "Girl, Interrupted (1999)"
  "Stand by Me (1986)"
  "Rob Roy (1995)"
  "Caligula (1980)"
  "Flirting With Disaster (1996)"
  "Hook (1991)"
  "Institute Benjamenta, or This Dream People Call Human Life (1995)"
  ⋮

In [22]:
# i šifre
values(rating_set.item_to_index)

Base.ValueIterator for a Dict{AbstractString,Int32} with 3706 entries. Values:
  594
  1361
  729
  1247
  3549
  2177
  996
  981
  669
  893
  1857
  1945
  2759
  2814
  1840
  39
  2670
  32
  85
  449
  2532
  1290
  657
  3397
  ⋮

In [23]:
# Koje je filmove ocijenio korisnik "3000"
user_ratings(rating_set, "3000")

96-element Array{Tuple{SubString{String},Float32},1}:
 ("American Beauty (1999)",5.0)                       
 ("Dances with Wolves (1990)",5.0)                    
 ("Brazil (1985)",5.0)                                
 ("Babe (1995)",5.0)                                  
 ("Caddyshack (1980)",5.0)                            
 ("Gattaca (1997)",5.0)                               
 ("Brothers McMullen, The (1995)",5.0)                
 ("When Harry Met Sally... (1989)",5.0)               
 ("One Flew Over the Cuckoo's Nest (1975)",5.0)       
 ("Twelve Monkeys (1995)",5.0)                        
 ("Time Bandits (1981)",5.0)                          
 ("Princess Bride, The (1987)",5.0)                   
 ("Chinatown (1974)",4.0)                             
 ⋮                                                    
 ("2001: A Space Odyssey (1968)",2.0)                 
 ("Romancing the Stone (1984)",2.0)                   
 ("Mission: Impossible (1996)",1.0)                   
 ("Blind Da

In [24]:
# Nađimo točan naziv i šifru za "Blade runner"
for k in keys(rating_set.item_to_index)
    if contains(k,"Blade")
        println(k)
    end
end

Sling Blade (1996)
Blade (1998)
Blade Runner (1982)
Some Folks Call It a Sling Blade (1993)


LoadError: LoadError: UnicodeError: invalid character index
while loading In[24], in expression starting on line 2

In [25]:
get(rating_set.item_to_index,"Blade Runner (1982)",0)

744

In [26]:
# Da li je korisnik "3000" ocijenio "Blade Runner" ?
for k in user_ratings(rating_set,"3000")
    if contains(k[1],"Blade")
        println(k)
    end
end

("Blade Runner (1982)",4.0f0)


In [27]:
# Da li je korisnik "3000" ocijenio "Citizen Kane" ?
for k in user_ratings(rating_set,"3000")
    if contains(k[1],"Citizen")
        println(k)
    end
end

In [28]:
# Ovo traje dvije i po minute
model = train(rating_set, 25);

Computing truncated rank 25 SVD 100% Time: 0:02:14


In [29]:
fieldnames(model)

5-element Array{Symbol,1}:
 :user_to_index
 :item_to_index
 :U            
 :S            
 :V            

In [30]:
model.U

6040×25 Array{Float32,2}:
 0.0105286   0.0108881    0.0169462    0.00726165  …   0.0165685   0.0105533 
 0.0143127   0.0107969    0.00958497   0.0103498       0.00717566  0.0150079 
 0.0101161   0.00902197   0.0170195    0.00770462      0.0117291   0.0157636 
 0.00710551  0.00677834   0.0158305    0.00420549      0.0114087   0.0111503 
 0.0136108   0.0157925    0.00125129   0.0154513       0.0038251   0.00905021
 0.0108928   0.0173633    0.0154919    0.0163003   …   0.00889664  0.0159288 
 0.00870144  0.00751549   0.0187289    0.00401489      0.0107074   0.0118996 
 0.0156788   0.0149871    0.00987733   0.0133478       0.0110488   0.0102954 
 0.0134843   0.0083181    0.010523     0.00702826      0.0111521   0.00816377
 0.0188921   0.0123215   -0.0108931    0.0242425       0.00759919  0.0124998 
 0.01271     0.0114213    0.0110434    0.0103405   …   0.011292    0.00321139
 0.00605743  0.00804548   0.0138675    0.00590076      0.0132224   0.0165833 
 0.0118863   0.00952506   0.0131845   

In [31]:
model.S

25-element Array{Float32,1}:
 8191.46  
 2145.75  
  823.595 
 1152.41  
  852.304 
 1202.16  
  638.137 
  404.692 
  331.272 
  254.959 
  260.26  
  346.955 
  284.287 
  226.332 
  258.695 
  315.226 
  341.985 
  192.93  
  205.88  
  195.595 
  171.799 
  140.685 
  136.543 
  115.004 
   97.6223

In [32]:
model.V

3706×25 Array{Float32,2}:
 0.0357308   0.00829067  0.0684244   …  -0.00427573    0.00211629
 0.025173    0.0150898   0.0205194      -0.00464182    0.00882804
 0.0305362   0.0132749   0.0311393      -0.0013124     0.00987835
 0.0320461   0.0118308   0.0538765       0.0193329    -0.02097   
 0.0315251   0.00753399  0.0547098       0.0118283    -0.0126033 
 0.0345476   0.00460288  0.0685182   …  -0.00493932   -0.00594212
 0.030664    0.00816449  0.029397        0.000558795   0.006811  
 0.0331358   0.00385654  0.0518303       0.0315574    -0.00627985
 0.0288807   0.00781605  0.0234186       0.00174335    0.0199391 
 0.0334986   0.00535404  0.0540243      -0.0167033     0.0369555 
 0.0296428   0.00542992  0.0376194   …   0.0203523    -0.0223229 
 0.0177424   0.0266619   0.0091863       0.00665131    0.0133215 
 0.025885    0.0189131   0.0132219       0.00282401    0.00724893
 ⋮                                   ⋱                           
 0.00118762  0.00260339  0.00408728      0.013889 

In [33]:
similar_items(model, "Friday the 13th (1980)")

10-element Array{SubString{String},1}:
 "Friday the 13th (1980)"                                    
 "Amityville Horror, The (1979)"                             
 "Jaws 2 (1978)"                                             
 "Friday the 13th Part 2 (1981)"                             
 "Omen, The (1976)"                                          
 "Pet Sematary (1989)"                                       
 "Nightmare on Elm Street Part 2: Freddy's Revenge, A (1985)"
 "Cujo (1983)"                                               
 "Candyman (1992)"                                           
 "Freddy's Dead: The Final Nightmare (1991)"                 

In [34]:
@which similar_items(model, "Friday the 13th (1980)")

similar_items(model::IncrementalSVD.RatingsModel, item) at /home/slap/.julia/v0.5/IncrementalSVD/src/util.jl:113

In [35]:
similar_items(model, "Citizen Kane (1941)")

10-element Array{SubString{String},1}:
 "Citizen Kane (1941)"                                                        
 "M*A*S*H (1970)"                                                             
 "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)"
 "Chinatown (1974)"                                                           
 "Rear Window (1954)"                                                         
 "Vertigo (1958)"                                                             
 "Lawrence of Arabia (1962)"                                                  
 "Casablanca (1942)"                                                          
 "Boat, The (Das Boot) (1981)"                                                
 "Apocalypse Now (1979)"                                                      

In [36]:
similar_users(model,"3000")

10-element Array{SubString{String},1}:
 "3000"
 "6030"
 "5619"
 "5457"
 "1360"
 "1817"
 "1248"
 "5572"
 "514" 
 "5368"

In [37]:
# Stvarna ocjena je bila 4.0
get_predicted_rating(model, "3000", "Blade Runner (1982)")

4.2329783f0

In [38]:
IncrementalSVD.get_predicted_rating(model, "3000", "Citizen Kane (1941)")

4.236797f0

## Tehnologija - github

Open Source!

[github](https://github.com) je sustav za kolaborativan razvoj softvera - izlog!


## Julia i Jupyter

[Julia](http://julialang.org/) je novi programski jezik (evolucija) za BigData

* [JuliaBox](https://juliabox.com/)

[Jupyter](http://jupyter.org/) bilježnice:
 
 * tekst i programi u 40 jezika (Julia, Python, R)
 * HTML, knjiga (LaTeX, PDF)
 * prezentacija, `nbgrader`

## Hvala na pažnji

Pitanja?