## Forward stable eigenvalue decomposition of real symmetric arrowhead matrices and rank-one modifications of diagonal matrices

Fakulteta za matematiko in fiziko - Univerza v Ljubljani


Ivan Slapničar, Sveučilište u Splitu, FESB

April 19, 2017

### Outline

* Algorithms, errors and perturbation theory
* Eigenvalue problem and perturbation theory
* Standard algorithms and errors
* Arrowhead matrices
    * inverses
    * algorithm and errors
    * SVD
* DPR1 matrices - algorithms and errors
* Deflation

### Algorithms, errors and perturbations

Let the value of the function $f(x)$ be computed using $\mathrm{alg(x)}$.

__The (forward) error__ is

$$
\|\mathrm{alg(x)}-f(x)\|,
$$

and __the relative error__ is 

$$
\frac{\| \mathrm{alg}(x)-f(x)\|}{\| f(x) \|}.
$$

### Perturbation theory

The change in $f(x)$ w.r.t. change of $x$ to $x+\delta x$ is

$$
\| f(x+\delta x)-f(x)\| \leq \frac{\| f(x+\delta x)-f(x)\|}{\| \delta x \|} \|\delta x\| \equiv \kappa \|\delta x\|.
$$

$\kappa$ is the __condition number__ (or __condition__) - reminds us of derivative.

Similarly, the _relative_ change in $f(x)$ w.r.t. _relative_ change of $x$ to $x+\delta x$ is

$$
\frac{\| f(x+\delta x)-f(x)\|}{\| f(x) \|}\leq \frac{\| f(x+\delta x)-f(x)\|\cdot  \|x\| }{\|\delta x\| \cdot\| f(x)\|}
\cdot \frac{\|\delta x\|}{\|x\|} \equiv \kappa \frac{\|\delta x\|}{\|x\|}
$$

### Backward errors

Forward erros are hard to estimate.

Instead, we consider  __backward error__

$$
\mathrm{alg}(x)=f(x+\delta x).
$$

Algorithm is __stable__ if  this always holds for some _small_ $\delta x$.

### Eigenvalues and eigenvectors

Let $F=\mathbb{R}$ or $F=\mathbb{C}$ and let $A\in F^{n\times n}$.

If $\exists (\lambda,x) \in F\times F^n$, such that $n\neq 0$ and

$$
Ax=\lambda x,
$$

then $\lambda$ is an __eigenvalue__ of $A$ and $x$ is an __eigenvector__ of $\lambda$.

### Schur decomposition


__Schur decomposition__ of $A$ is 

$$A=QTQ^*,$$

where $Q$ is unitary and $T$ is upper triangular. It always exists.

If $A$ is __normal__ ($AA^*=A^*A$), then $T$ is diagonal.

If, in addition, $A$ is __Hermitian__ ($A=A^*$), then $T$ is also real.

If, in addition, $A$ is real (real symmetric), then $Q$ is real, $A=Q\Lambda Q^T$.

### Perturbation theory

Notation: $\tilde A=A+\Delta A$ with eigenvalues $\tilde \Lambda$, $\tau$ is a permutation, 
$\kappa(A)=\|A\| \|A^{-1}\|$, $\sigma(A)$ is the spectrum of $A$.

__General__: $\|\Lambda- \tilde\Lambda_\tau\|_2\leq 4(\|A\|_2+\|\tilde A\|_2)^{1-1/n}\|\Delta A\|_2^{1/n}$

__Diagonalizable__ _(Bauer-Fike)_: If $A=X\Lambda X^{-1}$, then 

$$
\max_i\min_j |\tilde \lambda_i -
\lambda_j|\leq \|X^{-1}(\Delta A)X\|_p\leq \kappa_p(X)\|\Delta A\|_p
$$

### Perturbation theory

__Both diagonalizable__:
$\|\Lambda-\tilde\Lambda_\tau\|_F\leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_F
$

$\Lambda$ and  $\tilde\Lambda$ real:
$
\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\|_{2,F} \leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_{2,F}
$

__Normal__:
$
\|\Lambda-\tilde\Lambda_\tau\|_F\leq\sqrt{n}\|\Delta A\|_F
$


__Both normal__ _(Hoffman-Wielandt)_:
$
\|\Lambda-\tilde\Lambda_\tau\|_F\leq\|\Delta A\|_F
$


### Perturbation theory


__Both Hermitian__: for any unitarily invariant norm 
$\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\| \leq \|\Delta A\|$

In particular,

\begin{align*}
\max_i|\lambda^\uparrow_i-\tilde\lambda^\uparrow_i|&\leq \|\Delta A\|_2\\ 
\sqrt{\sum_i(\lambda^\uparrow_i-\tilde\lambda^\uparrow_i)^2}&\leq \|\Delta A\|_F
\end{align*}


### Residual bounds for Hermitian matrices

For some $\tilde\lambda\in\mathbb{R}$ and $\tilde x\in\mathbb{C}^n$, $\|\tilde x\|_2=1$, define __residual__ 
$
r=A\tilde x-\tilde\lambda\tilde x
$.

Then $|\tilde\lambda-\lambda|\leq \|r\|_2$ for some $\lambda\in\sigma(A)$.

Let, in addition,  $\tilde\lambda=\tilde x^* A\tilde x$, let $\lambda$ be closest to $\tilde\lambda$ and $x$ be its unit eigenvector, and let 
$$\eta=\mathop{\mathrm{gap}}(\tilde\lambda)= \min_{\lambda\neq\mu\in\sigma(A)}|\tilde\lambda-\mu|.$$
If $\eta>0$, then

$$ |\tilde\lambda-\lambda|\leq \frac{\|r\|_2^2}{\eta},\quad \sin\theta(x,\tilde x)\leq \frac{\|r\|_2}{\eta}.
$$


### Algorithms - Power method

$A$ is real symmetric and $A=U\Lambda U^T$ is its EVD.

__Power method__ starts from vector $x_0$ and computes the sequences

$$
\nu_k=x_k^T A x_k, \qquad x_{k+1}= A x_k /
 \| A x_k \|, \qquad k=0,1,2,\dots
$$

If $|\lambda_1|> |\lambda_2| \geq \cdots \geq |\lambda_n|$,
and if  $x_0=\sum c_i U_{:i}$, then

$$
|\lambda_1-\nu_k|\approx \left|\frac{c_2}{c_1}\right| \left|
 \frac{\lambda_2}{\lambda_1}\right|^k,\qquad
\|U_{:1}-x_k\|_2 =O\bigg(\bigg|
 \frac{\lambda_2}{\lambda_1}\bigg|^k\bigg)\!.
$$

### Inverse iteration

is the power method applied to the inverse of
a _shifted matrix_:

$$
\nu_k=x_k^T A x_k, \
x_{k+1}= (A-\mu I)^{-1} x_k, \ 
x_{k+1} = x_{k+1}/\|x_{k+1}\|, \ k=0,1,2,\dots
$$

Notice $A-\mu I=U(\Lambda-\mu I) U^T$.  

Inverse iteration requires solving the system of linear equations 
$(A-\mu I)x_{k+1}= x_k$ in each step. 

If $\mu$ is very close to some $\lambda_i$, then $|\lambda_i-\mu|\gg
|\lambda_j-\mu|$ for all $j\neq i$, so the convergence is fast.
The solutions of linear systems may have large errors. However, these errors are almost
entirely in the direction of the dominant eigenvector so the method is accurate.

###  QR iteration

starts from the matrix $A_0=A$ and forms the sequence of matrices

$$
  A_k=Q_kR_k \ \textrm{(factorization)}, \quad
  A_{k+1}=R_kQ_k,\quad k=0,1,2,\ldots 
$$

__Shifted QR iteration__ is the QR iteration applied to a shifted matrix:

$$
A_k-\mu I=Q_kR_k \ \textrm{(factorization)}, \quad
  A_{k+1}=R_kQ_k+\mu I ,\quad k=0,1,2,\ldots 
$$

QR iteration is essentially equivalent to the power method and the shifted QR iteration is essentially equivalent to the inverse power method. 

### Practical QR method

1. Reduce $A$ to tridiagonal form $T$ by orthogonal similarities, $X^TAX=T$
2. Compute the EVD of $T$, $T=Q\Lambda Q^T$ 
3. Multiply $U=XQ$

There are many methods for step 2: QR iterations, bisection and inverse iteration, D&C, MRRR, all requiring $O(n^2)$ operations.

### Error bounds

All previous methods have backward errors s.t. $\| \Delta A \| \leq O(\epsilon) \|A\|$.

More precisely, let $\tilde U \tilde \Lambda \tilde U^T$ be the computed EVDs of $A$.
Then

$$
|\lambda_i-\tilde \lambda_i|\leq \phi \epsilon\|A\|_2,
\qquad
\|u_i-\tilde u_i\|_2\leq \psi\epsilon \frac{\|A\|_2}
{\min_{j\neq i} 
|\lambda_i-\tilde \lambda_j|}
$$

$\epsilon$ is machine precision, $\phi$ and $\psi$
are slowly growing polynomial functions of
$n$ (typically $O(n)$ or $O(n^2)$).
Such bounds are obtained by combining perturbation bounds with the floating-point error analysis of the respective
algorithm.


### Relative perturbation theory

$A$  is a real symmetric positive definite (PD) matrix, $\lambda_i>0$.

The __scaled matrix__ of $A$ is the matrix
$A_S=D^{-1} A D^{-1}$, $D=\mathop{\mathrm{diag}}(\sqrt{A_{11}},\sqrt{A_{22}},\ldots,\sqrt{A_{nn}})$.

This scaling is nearly optimal: 
$\kappa_2(A_S)\leq  n \min\limits_{D=\mathrm{diag}} \kappa(DHD) \leq n\kappa_2(H)$.

If $\tilde A=A+\Delta A$ is PD, then [Demmel, Barlow, Veselić, Drmač, Li,...] 

$$
\frac{|\lambda_i-\tilde\lambda_i|}{\lambda_i}\leq 
\frac{\| D^{-1} (\Delta A) D^{-1}\|_2}{\lambda_{\min} (A_S)}\equiv
\|A_S^{-1}\|_2 \| \Delta A_S\|_2.
$$

### Relative perturbation theory

If $\lambda_i$ and $\tilde\lambda_i$ are simple, then

$$
\|U_{:,i}-\tilde U_{:,i}\|_2 \leq \frac{\| A_S^{-1}\|_2 \|\Delta A_S\|_2}
{\displaystyle\min_{j\neq i}\frac{|\lambda_i-\lambda_j|}{\sqrt{\lambda_i\lambda_j}}}.
$$

These bounds are much sharper than the standard bounds when $\kappa_2(A_S)\ll \kappa_2(A)$.

### Jacobi method and relative error bounds

__Jacobi method__ forms a sequence of matrices,

$$
A_0=A, \qquad A_{k+1}=G(i_k,j_k,c,s) A_k G(i_k,j_k,c,s)^T, \qquad
k=1,2,\ldots,
$$

where $G(i_k,j_k,c,s)$ is the orthogonal __plane rotation matrix__, and $c$ and $s$ are chosen such that 
$[A_{k+1}]_{i_k j_k}=[A_{k+1}]_{j_k i_k}=0$.

Jacobi method with the relative stopping criterion $|A_{ij}|\leq tol \sqrt{A_{ii}A_{jj}}$ for all $i\neq j$ (usually $tol=n\varepsilon$), computes the EVD with small __scaled__ backward error $\|\Delta A_S\|\leq \varepsilon\, O(\|A_S\|_2)\leq O(n)\varepsilon$, __provided__ that $\kappa_2([A_k]_S)$  does not grow much during the iterations. [Demmel, Veselić]

In [1]:
function myJacobi{T}(A::Array{T})
    n,m=size(A)
    U=eye(T,n)
    # Tolerance for rotation
    tol=sqrt(n)*eps(T)
    # Counters
    p=n*(n-1)/2
    sweep=0
    pcurrent=0
    # First criterion is for standard accuracy, second one is for relative accuracy
    # while sweep<30 && vecnorm(A-diagm(diag(A)))>tol
    while sweep<30 && pcurrent<p
        sweep+=1
        # Row-cyclic strategy
        for i = 1 : n-1 
            for j = i+1 : n
                # Check the tolerance - the first criterion is standard,
                # the second one is for relative accuracy for PD matrices               
                # if A[i,j]!=zero(T)
                if abs(A[i,j])>tol*sqrt(abs(A[i,i]*A[j,j]))
                    # Compute c and s
                    τ=(A[i,i]-A[j,j])/(2*A[i,j])
                    t=sign(τ)/(abs(τ)+sqrt(1+τ^2))
                    c=1/sqrt(1+t^2)
                    s=c*t
                    G=LinAlg.Givens(i,j,c,s)
                    A=G*A
                    # @show
                    A*=G'
                    A[i,j]=zero(T)
                    A[j,i]=zero(T)
                    U*=G'
                    pcurrent=0
                else
                    pcurrent+=1
                end
            end
        end
    end
    # λ, U
    # @show A
    diag(A), U
end

myJacobi (generic function with 1 method)

In [2]:
n=6
A=rand(-9:9,n,n)
A=A*A'

6×6 Array{Int64,2}:
 122    2  -21  -76   28   21
   2  132  -17  140   60  -12
 -21  -17   84   15  -37  -67
 -76  140   15  229   50  -59
  28   60  -37   50   82   49
  21  -12  -67  -59   49  148

In [3]:
AS=map(Float64,[A[i,j]/sqrt(A[i,i]*A[j,j]) for i=1:n, j=1:n])

6×6 Array{Float64,2}:
  1.0         0.0157603  -0.207443  -0.454691   0.279944   0.156282 
  0.0157603   1.0        -0.161444   0.805236   0.57671   -0.0858546
 -0.207443   -0.161444    1.0        0.108152  -0.445815  -0.600903 
 -0.454691    0.805236    0.108152   1.0        0.364876  -0.320482 
  0.279944    0.57671    -0.445815   0.364876   1.0        0.444793 
  0.156282   -0.0858546  -0.600903  -0.320482   0.444793   1.0      

In [4]:
cond(AS), cond(A)

(63.531058220405455,64.04177835616379)

In [5]:
# Strong scaling
D=exp(50*(rand(n)-0.5))

6-element Array{Float64,1}:
 7.41721e-5
 1.63375e-7
 6.79371e6 
 3.09305e-7
 1.82297e8 
 6.41459   

In [6]:
A=diagm(D)*AS*diagm(D)

6×6 Array{Float64,2}:
    5.50149e-9    1.9098e-13   -104.531       …  3785.21         7.43563e-5
    1.9098e-13    2.66914e-14    -0.17919          17.176       -8.99741e-8
 -104.531        -0.17919         4.61545e13       -5.52129e14  -2.61866e7 
   -1.04314e-11   4.06908e-14     0.227263         20.5737      -6.35857e-7
 3785.21         17.176          -5.52129e14        3.32321e16   5.20123e8 
    7.43563e-5   -8.99741e-8     -2.61866e7   …     5.20123e8   41.1469    

In [7]:
cond(A)

1.3048631512985587e30

In [8]:
λ,U=myJacobi(A)

([5.02261e-9,2.29512e-15,3.6971e13,3.58443e-14,3.32413e16,24.6824],
[0.999997 -0.00110471 … 1.13907e-13 -1.88135e-7; -0.000339249 0.823785 … 5.16725e-16 -1.24958e-8; … ; -9.66522e-14 1.80376e-16 … 0.999862 -7.7688e-9; 1.88062e-7 -5.71287e-9 … 1.56578e-8 1.0])

In [9]:
λ1,U1=eig(A)

([3.32413e16,3.6971e13,24.6824,-0.000132288,5.50066e-14,0.00252215],
[1.14136e-13 -1.12402e-12 … 9.26906e-8 -7.87273e-10; 2.46992e-16 4.79525e-15 … 9.72615e-12 1.0; … ; 0.999862 0.0166305 … 1.0924e-15 -7.56716e-16; 1.56578e-8 -4.7424e-7 … -2.78688e-8 1.22934e-8])

In [10]:
[sort(λ) sort(λ1)]

6×2 Array{Float64,2}:
  2.29512e-15  -0.000132288
  3.58443e-14   5.50066e-14
  5.02261e-9    0.00252215 
 24.6824       24.6824     
  3.6971e13     3.6971e13  
  3.32413e16    3.32413e16 

In [11]:
# Check with BigFloat
λ2,U2=myJacobi(map(BigFloat,A))

(BigFloat[5.022614877781149125539210164929030420146746773515899696960643187317643046577704e-09,2.295123812804994670064398624978608626094419879330841147247327958758049463352806e-15,3.69709760989353391999716039607013085617023550846726252497535938803637609775443e+13,3.58442908604202048887119888314880706877507542982825120427202388597308838743938e-14,3.324128602639678860975071153952176645799736210731727702874912594775807140907954e+16,2.46823555145719291121145500883882866290457481725366572554375047580039138063829e+01],
BigFloat[9.999969615982539377331101147559754452834275528414717672736964140575748516894691e-01 -1.104713724270534496826238635189559126469097833676912650859732520535158609448299e-03 … 1.139074123223364507094259086863585769557234380818640483261349979571726790219396e-13 -1.881351158755531512751902132523613243002881035801779816506469374670225736025187e-07; -3.392490770226965414700324549475980750803308066749211580480332613491578980333178e-04 8.237854061465595798489599735011879903427

In [12]:
# Relative error is eps()*cond(AS)
(sort(λ2)-sort(λ))./sort(λ2)

6-element Array{BigFloat,1}:
 -2.608544515585232496093839344125106270207557409753143511686891006658419464596948e-15
 -2.194318804006210569268021934621652226307993757473709030414239287652003141389973e-16
 -6.181600905183360108694538884417831953010804722380976622056949928184373641940984e-16
 -8.006272606869755098814876291906572791964006933460485022962800990262987772746052e-16
  8.824412953637573485953240920331026994216541576126251131895845905576149340265213e-17
 -1.01989113350436958664433563068197557638015726028122315319920090332616898843922e-16 

###  Indefinite matrices

__Spectral absolute value__ is $|A|_{spr}=(A^2)^{1/2}$ (PD part of the polar decomposition of $A$).

The relative perturbation bounds for PD matrices essentially hold with $A_S$ replaced by $[|A|_{spr}]_S$.

Jacobi method can be modified to compute the EVD with small backward error  $\| \Delta [|A|_{spr}]_S\|_2$. [S.]

### Singular value decomposition

Let $A\in\mathbb{C}^{m\times n}$ and let $q=\min\{m,n\}$.

The SVD of $A$ is $A=U\Sigma V^*$,
where $U\in\mathbb{C}^{m\times m}$ and $V\in\mathbb{C}^{n\times n}$ are unitary, and 
$\Sigma=\mathop{\mathrm{diag}}(\sigma_1,\sigma_2,\ldots,\sigma_q)\in\mathbb{R}^{m\times n}$ with all 
$\sigma_j\geq 0$.

SVD is related to EVDs $A^*A=V\Sigma^T\Sigma V^*$ and $AA^*=U\Sigma\Sigma^TU^*$. Eigenvalues of 
the __Jordan-Wielandt__ matrix 

$$
J=\begin{bmatrix}0 & A \\ A^* & 0 \end{bmatrix}
\in \mathbb{C}^{(m+n) \times (m+n)},
$$

are $\pm \sigma_1(A), \pm\sigma_2(A), \cdots,\pm\sigma_q(A)$ together with $|m-n|$ zeros.


### Perturbation theory

Bounds analogous to those for PD matrices hold, for example _(Mirsky)_: 
$\|\Sigma-\tilde\Sigma\|_2\leq \|\Delta A\|_2$ and  $\|\Sigma-\tilde\Sigma\|_F\leq \|\Delta A\|_F$.

Relative perturbation bounds involve __graded__ matrices $A=GD$, where $D=\mathrm{\mathop{diag}}(\| A_{:i}\|_2$, and are efficient when $\kappa(G)\ll \kappa(A)$, for example [Demmel, Veselić, Drmač,...]

$$
\frac{|\sigma_i-\tilde\sigma_i|}{\sigma_i}\leq 
\|G^{\dagger}\|_2 \| \Delta G\|_2.
$$

### Algorithms and error bounds

Standard algorithm is 

1. Reduce $A$ to bidiagonal form $B$, $X^TAY=B$
2. Compute the SVD of $B$, $B=Z\Sigma Q^T$ 
3. Multiply $U=XZ$ and $V=YQ$

Step 1 can preserve relative accuracy [Barlow, Bosner, Drmač].
Step 2 can preserve high relative accuracy [Demmel, Kahan - LAPACK dbdsqr.f, SIAG/LA Prize 1991]

One-sided Jacobi computes the SVD with high relative accuracy [DDGESVD], [Drmač, Veselić - LAPACK dgesvj.f, SIAG/LA Prize 2009]


### Acyclic matrices

Matrices whose bipartite graph is acyclic preserve their singular values under small componentwise perturbations [Demmel, Gragg]. Examples are

1. bidiagonal matrix (path)
2. half-arrowhead matrix (star)

For example, $\varepsilon$ relative changes in diagonal and super-diagonal elements of bidiagonal matrix, cause at most $(2n-1)\varepsilon$ relative changes in the singular values.

In [17]:
# Singular values of a Jordan block - Veselić
n=100
# The starting matrix
a=0.5*ones(n)
b=ones(n-1)
A=Bidiagonal(a,b, true)

100×100 Bidiagonal{Float64}:
 0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅  

In [18]:
σ=svdvals(A)
U,σ1,V=svd(A)
[σ σ1]

100×2 Array{Float64,2}:
 1.49984      1.49984    
 1.49935      1.49935    
 1.49853      1.49853    
 1.49739      1.49739    
 1.49592      1.49592    
 1.49412      1.49412    
 1.492        1.492      
 1.48956      1.48956    
 1.48679      1.48679    
 1.4837       1.4837     
 1.48029      1.48029    
 1.47656      1.47656    
 1.47251      1.47251    
 ⋮                       
 0.556938     0.556938   
 0.547576     0.547576   
 0.538931     0.538931   
 0.531049     0.531049   
 0.523973     0.523973   
 0.517744     0.517744   
 0.512401     0.512401   
 0.507979     0.507979   
 0.504507     0.504507   
 0.502009     0.502009   
 0.500503     0.500503   
 5.91646e-31  2.04866e-30

In [20]:
(σ-σ1)./σ

100-element Array{Float64,1}:
  0.0        
  2.96189e-16
  1.48175e-16
  1.48288e-16
  1.48434e-16
  1.48612e-16
  0.0        
  2.98134e-16
  4.48034e-16
  4.48967e-16
  6.00002e-16
  3.00759e-16
  1.50793e-16
  ⋮          
  0.0        
  0.0        
  2.06005e-16
 -8.36249e-16
 -2.11886e-16
 -4.2887e-16 
 -6.50012e-16
 -2.18557e-16
  0.0        
  0.0        
  2.21821e-16
 -2.46264    

### Arrowhead and DPR1 matrices



__Arrowhead__: 
$A=\begin{bmatrix} D & z \\ z^{T} & \alpha \end{bmatrix}$,
$D=\mathop{\mathrm{diag}}(d_{1}, \ldots ,d_{n-1})$, 
$z=\begin{bmatrix} \zeta _{1} & \cdots & \zeta _{n-1} \end{bmatrix}^T$,
$\alpha\in\mathbb{R}$

__DPR1__: $A= D +\rho z z^T$, $D=\mathop{\mathrm{diag}}(d_{1},\ldots ,d_{n})$, 
$z=\begin{bmatrix} \zeta _{1} & \cdots & \zeta _{n} \end{bmatrix}^T$, $\rho \neq 0\in\mathbb{R}$

If $\zeta _{i}=0$, then $(d_{i},e_{i})$ is an eigenpair. If $d_{i}=d_{j}$, then $d_{i}$ is
an eigenvalue since $\zeta_j$ can be annihilated by a Givens rotation in the $(i,j)$-plane.

Matrices are __irreducible__ if 
$\zeta _{i}\neq 0$ for all $i$ and $d_{i}\neq d_{j}$ for all $i\neq j$.

### Interlacing

Let $A=U\Lambda U^T$ be the EVD of an irreducible arrowhead.
If $d_i$ and $\lambda_i$ are nonincreasingy ordered, then

$$\lambda _{1}> d_{1}> \lambda _{2}> d_{2}> \cdots > d_{n-2}>\lambda
_{n-1}> d_{n-1}> \lambda _{n}.
$$

Let $A=U\Lambda U^T$ be the EVD of an irreducible DPR1. 
If $d_i$ and $\lambda_i$ are nonincreasingy ordered, then

$$\lambda _{1}> d_{1}> \lambda _{2}> d_{2}> \cdots > d_{n-2}>\lambda
_{n-1}> d_{n-1}> \lambda _{n}> d_n.
$$



### Arrowhead EVD

The eigenvalues $\lambda_i$ are the zeros of the __Pick function__

$$
f(\lambda )=\alpha -\lambda -\sum_{i=1}^{n-1}\frac{\zeta _{i}^{2}}{%
d_{i}-\lambda }=\alpha -\lambda -z^{T}(D-\lambda I)^{-1}z,
$$

and the corresponding eigenvectors are 

$$
U_{:,i}=\frac{x_{i}}{\left\Vert x_{i}\right\Vert _{2}},\quad 
x_{i}=\begin{bmatrix}
\left( D-\lambda _{i}I\right) ^{-1}z \\ 
-1%
\end{bmatrix}, 
\quad i=1,\ldots ,n.
$$

### DPR1 EVD

The eigenvalues of $A$ are the zeros of the __secular equation__ 

$$
f(\lambda )=1+\rho\sum_{i=1}^{n}\frac{\zeta _{i}^{2}}{d_{i}-\lambda }
=1 +\rho z^{T}(D-\lambda I)^{-1}z=0,
$$

and the corresponding eigenvectors are 

$$
U_{:,i}=\frac{x_{i}}{\left\Vert x_{i}\right\Vert _{2}},\quad
x_{i}=( D-\lambda _{i}I) ^{-1}z.
$$

The obvious $O(n)$ algorithms (per eigenpair) are inaccurate.

### Structured inverses (arrowhead)

If $d_i\neq 0$ for all $i$, then

$$
A^{-1}=\begin{bmatrix} D^{-1} &  \\ & 0 \end{bmatrix} + \rho uu^{T}, \
u=\begin{bmatrix} z^{T}D^{-1} \\ -1 \end{bmatrix}, \ \rho =\displaystyle\frac{1}{\alpha-z^{T}D^{-1}z}.
$$

This and subsequent inverses are each computable in $O(n)$ flops.

### Structured inverses (arrow. with zero pole)

If $d_i=0$, then

$$
A^{-1}\equiv 
\begin{bmatrix}
D_{1} & 0 & 0 & z_{1} \\ 
0 & 0 & 0 & \zeta _{i} \\ 
0 & 0 & D_{2} & z_{2} \\ 
z_{1}^{T} & \zeta _{i} & z_{2}^{T} & \alpha
\end{bmatrix}^{-1}
= \begin{bmatrix}
D_{1}^{-1} & w_{1} & 0 & 0 \\ 
w_{1}^{T} & b & w_{2}^{T} & 1/\zeta _{i} \\ 
0 & w_{2} & D_{2}^{-1} & 0 \\ 
0 & 1/\zeta _{i} & 0 & 0
\end{bmatrix},
$$

$w_{1}=-D_{1}^{-1}z_{1}\displaystyle\frac{1}{\zeta _{i}}$, 
$w_{2}=-D_{2}^{-1}z_{2}\displaystyle\frac{1}{\zeta _{i}}$,
$b= \displaystyle\frac{1}{\zeta _{i}^{2}}\left(-\alpha +z_{1}^{T}D_{1}^{-1}z_{1}+z_{2}^{T}D_{2}^{-1}z_{2}\right)$.

### Structured inverses (DPR1)

If $d_i\neq 0$ for all $i$, then

$$
A^{-1}=D^{-1} +\gamma uu^{T},\quad  u=D^{-1}z, \quad \gamma =-\frac{\rho}{1+\rho z^{T}D^{-1}z}.
$$ 

### Structured inverses (DPR1 with zero pole)

If $d_i=0$, then

$$
A^{-1}\equiv \left(\begin{bmatrix} D_{1} & 0 & 0 \\  0 & 0 & 0  \\  0 & 0 & D_{2} \end{bmatrix}
+\rho \begin{bmatrix} z_{1} \\ \zeta _{i} \\ z_{2}
\end{bmatrix}
\begin{bmatrix}
z_{1}^{T} & \zeta _{i} & z_{2}^{T}
\end{bmatrix}\right)^{-1}=
\begin{bmatrix}
D_{1}^{-1} & w_{1} & 0 \\ 
w_{1}^{T} & b & w_{2}^{T} \\ 
0 & w_{2} & D_{2}^{-1} 
\end{bmatrix},
$$

$w_{1}=-D_{1}^{-1}z_{1}\displaystyle\frac{1}{\zeta _{i}}$,
$w_{2}=-D_{2}^{-1}z_{2}\displaystyle\frac{1}{\zeta _{i}}$,
$b =\displaystyle\frac{1}{\zeta _{i}^{2}}\left(
\frac{1}{\rho}+z_{1}^{T}D_{1}^{-1}z_{1}+z_{2}^{T}D_{2}^{-1}z_{2}\right)$.

### Idea

Let $\lambda_\max$ be the absolutely largest eigenvalue. 

It is computed with high relative accuracy by any reasonable algorithm:

$$
\frac{\big|\lambda_\max -\tilde \lambda_\max\big|}{\big|\lambda_\max\big|}\leq 
\frac{\|\Delta A\|_2}{\big|\lambda_\max\big|}=
\frac{\epsilon \|A\|_2}{\big|\lambda_\max\big|}\equiv \epsilon.
$$

### Algorithms

The algorithms based on the following approach compute all eigenvalues and _all components_ of the corresponding eigenvectors in a forward stable manner to almost full accuracy in $O(n)$ operations per eigenpair:

1. Shift the irreducible $A$ to $d_i$ which is closer to $\lambda_i$ (one step of bisection on $f(\lambda)$).
2. Invert the shifted matrix. 
3. Compute the absolutely largest eigenvalue of the inverted shifted matrix and the corresponding eigenvector.

### Numerical issues

1. All elements of the inverses of the shifted matrices are highly accurate, except possibly $b$ (or $\rho$ or $\gamma$). If these are not accurate, compute them using extended precision.

2. If two eigenvalues are close to the same pole, one much nearer than the other, some modifications are necessary. 

The algorithms are implemented in the package [Arrowhead.jl](https://github.com/ivanslapnicar/Arrowhead.jl). 

For double the working the package [DoubleDouble.jl](https://github.com/simonbyrne/DoubleDouble.jl) is used.

In [22]:
using Arrowhead

In [23]:
whos(Arrowhead)

                     Arrowhead     30 KB     Module
                  GenHalfArrow      0 bytes  Arrowhead.#GenHalfArrow
                   GenSymArrow      0 bytes  Arrowhead.#GenSymArrow
                    GenSymDPR1      0 bytes  Arrowhead.#GenSymDPR1
                     HalfArrow    180 bytes  DataType
                      SymArrow    204 bytes  DataType
                       SymDPR1    192 bytes  DataType
                        bisect      0 bytes  Arrowhead.#bisect
                           eig      0 bytes  Base.LinAlg.#eig
                           inv      0 bytes  Base.#inv
                      rootsWDK      0 bytes  Arrowhead.#rootsWDK
                       rootsah      0 bytes  Arrowhead.#rootsah
                           svd      0 bytes  Base.LinAlg.#svd
                           tdc      0 bytes  Arrowhead.#tdc


In [24]:
methods(GenSymArrow)

# 1 method for generic function "GenSymArrow":
GenSymArrow(n::Integer, i::Integer) at /home/slap/.julia/v0.5/Arrowhead/src/arrowhead3.jl:8

In [25]:
n=10
A=GenSymArrow(n,n)

10×10 Arrowhead.SymArrow{Float64}:
 0.453542  0.0       0.0       0.0       …  0.0       0.0       0.131899
 0.0       0.871093  0.0       0.0          0.0       0.0       0.275898
 0.0       0.0       0.331778  0.0          0.0       0.0       0.742005
 0.0       0.0       0.0       0.926726     0.0       0.0       0.760486
 0.0       0.0       0.0       0.0          0.0       0.0       0.939198
 0.0       0.0       0.0       0.0       …  0.0       0.0       0.850031
 0.0       0.0       0.0       0.0          0.0       0.0       0.411949
 0.0       0.0       0.0       0.0          0.712166  0.0       0.119034
 0.0       0.0       0.0       0.0          0.0       0.831051  0.660494
 0.131899  0.275898  0.742005  0.760486     0.119034  0.660494  0.353341

In [26]:
fieldnames(A)

4-element Array{Symbol,1}:
 :D
 :z
 :a
 :i

In [27]:
A.D, A.z, A.a, A.i

([0.453542,0.871093,0.331778,0.926726,0.530604,0.706746,0.197764,0.712166,0.831051],[0.131899,0.275898,0.742005,0.760486,0.939198,0.850031,0.411949,0.119034,0.660494],0.3533409535050327,10)

In [28]:
tols=[1e2,1e2,1e2,1e2,1e2]
U,λ=eig(A,tols)
norm(full(A)*U-U*diagm(λ)), norm(U'*U-I)

(1.4049302989074133e-15,5.061490338324402e-16)

In [31]:
# Timings - notice the O(n^2)
@time eig(GenSymArrow(1000,1000),tols);
@time eig(GenSymArrow(2000,2000),tols);

  0.420271 seconds (1.08 M allocations: 122.141 MB, 17.60% gc time)
  1.177007 seconds (4.12 M allocations: 475.173 MB, 1.95% gc time)


In [32]:
# Numerically demanding matrix
A=SymArrow( [ 1e10+1.0/3.0, 4.0, 3.0, 2.0, 1.0 ], 
[ 1e10 - 1.0/3.0, 1.0, 1.0, 1.0, 1.0 ], 1e10, 6 )

6×6 Arrowhead.SymArrow{Float64}:
 1.0e10  0.0  0.0  0.0  0.0  1.0e10
 0.0     4.0  0.0  0.0  0.0  1.0   
 0.0     0.0  3.0  0.0  0.0  1.0   
 0.0     0.0  0.0  2.0  0.0  1.0   
 0.0     0.0  0.0  0.0  1.0  1.0   
 1.0e10  1.0  1.0  1.0  1.0  1.0e10

In [34]:
U,λ=eig(A,tols)
λ

6-element Array{Float64,1}:
  2.0e10  
  4.17472 
  3.18832 
  2.22325 
  1.26185 
 -0.348142

In [35]:
U

6×6 Array{Float64,2}:
 -0.707107      0.16715     0.175055    0.201186   0.230118    0.589904
 -3.53553e-11  -0.956659    0.21567     0.113232   0.0840413   0.135668
 -3.53553e-11  -0.142289   -0.929569    0.25901    0.132392    0.176188
 -3.53553e-11  -0.0768603  -0.147313   -0.901161   0.31175     0.251222
 -3.53553e-11  -0.0526502  -0.0799952  -0.164468  -0.878813    0.437568
 -0.707107     -0.16715    -0.175055   -0.201186  -0.230118   -0.589904

In [37]:
λ1,U1=eig(full(A))
λ1

6-element Array{Float64,1}:
 -0.348142
  1.26185 
  2.22325 
  3.18832 
  4.17472 
  2.0e10  

In [38]:
U1

6×6 Array{Float64,2}:
 -0.589904   0.230118   -0.201186   0.175055    0.16715    -0.707107   
 -0.135668   0.0840414  -0.113232   0.21567    -0.956659   -3.53553e-11
 -0.176188   0.132392   -0.25901   -0.929568   -0.142289   -3.53553e-11
 -0.251222   0.31175     0.901161  -0.147313   -0.0768603  -3.53553e-11
 -0.437568  -0.878813    0.164468  -0.0799953  -0.0526502  -3.53553e-11
  0.589904  -0.230118    0.201186  -0.175055   -0.16715    -0.707107   

In [41]:
(sort(λ)-sort(λ1))./sort(λ)

6-element Array{Float64,1}:
  1.17284e-6 
 -4.90798e-8 
 -2.13464e-8 
 -1.12719e-8 
 -7.84919e-9 
 -1.71661e-15

In [86]:
U[2,1]

-3.5355339066398446e-11

In [87]:
U1[end-1,end]

-3.5355274263793035e-11

In [88]:
# Numerically demanding DPR1 matrix
A=SymDPR1( [ 10.0/3.0, 2.0+1e-7, 2.0-1e-7, 1.0 ], [ 2.0, 1e-7, 1e-7, 2.0], 1.0 )
A = SymDPR1( [ 1e10, 5.0, 4e-3, 0.0, -4e-3,-5.0 ], [ 1e10, 1.0, 1.0, 1e-7, 1.0,1.0 ], 1.0 )

6×6 Arrowhead.SymDPR1{Float64}:
    1.0e20  1.0e10  1.0e10  1000.0      1.0e10   1.0e10
    1.0e10  6.0     1.0        1.0e-7   1.0      1.0   
    1.0e10  1.0     1.004      1.0e-7   1.0      1.0   
 1000.0     1.0e-7  1.0e-7     1.0e-14  1.0e-7   1.0e-7
    1.0e10  1.0     1.0        1.0e-7   0.996    1.0   
    1.0e10  1.0     1.0        1.0e-7   1.0     -4.0   

In [89]:
fieldnames(A)

3-element Array{Symbol,1}:
 :D
 :u
 :r

In [90]:
U,λ=eig(A,tols)
norm(full(A)*U-U*diagm(λ)), norm(U'*U-I)

Remedy 3 


(3.0381820395446957e-6,2.2204460858891437e-16)

In [92]:
[sort(λ) sort(eigvals(full(A)))]

6×2 Array{Float64,2}:
 -5.0      -5.0        
 -0.004    -5.74215e-14
  1.0e-24   5.62712e-14
  0.004     0.004      
  5.0       5.0        
  1.0e20    1.0e20     

## Hvala na pažnji

Pitanja?